### ISSUE TITLE
Is it possible to mask a text with this textfield?

### ISSUE THREAD

**Issue by giovanischiar** [n4kz/react-native-material-textfield#100]
I'd like to use this TextField with a mask just like this component: https://www.npmjs.com/package/react-native-text-input-mask it is possible?

**Comment by AlexisLeon** [comment]
You can use [Redux form](https://redux-form.com/7.3.0/examples/normalizing/) normalizing property

**Comment by Noitidart** [comment]
@AlexisLeon I use redux-form extensively. It gives a different styling/shape etc when you apply a mask. It is not at all the same thing. I did ask about this on their repo there if it works with redux-form and they said yes it does. I haven't yet tried it though.

**Comment by AlexisLeon** [comment]
@Noitidart As I see it,  the only way to use input-mask component with material-textfield styling is modifying [react-native-text-input-mask](https://github.com/react-native-community/react-native-text-input-mask/blob/master/index.js#L49) so it can render material's `TextField` as a custom component; redux-form seems to be the way to go if you don't want to open a PR or having an outdated component

```diff
static defaultProps = {
    maskDefaultValue: true,
+  component: TextInput,
}

render() {
+  return (<this.props.component
    {...this.props}
    value={undefined}
```
OR:
```diff
render() {
+   const Input = this.props.component || TextInput;
+   return (<Input
    {...this.props}
    value={undefined}
```

**Comment by Noitidart** [comment]
Thank you sir for your awesome awesome in depth research. I would love to use masking some day too, your post here will be a great starting point!

**Comment by odesey** [comment]
Hey @AlexisLeon  do you have a working example repo of `input-mask` + `material-textfield`?

**Comment by AlexisLeon** [comment]
@odesey no, sorry.

**Comment by himanshug16** [comment]
@AlexisLeon @Noitidart @odesey . I don't know if that helps but i struggled with the same thing for masking phone number as client's requirement was to use material textfield only because of the field animation.So i did something like this:

numberFormat(text) {
      let maskPhone = text.replace(/\D/g, '').match(/(\d{0,3})(\d{0,3})(\d{0,4})/);
      this.setState({
        businessPhone: !maskPhone[2] ? maskPhone[1] : '(' + maskPhone[1] + ') ' + maskPhone[2] + (maskPhone[3] ? '-' + maskPhone[3] : '')
      });
   }

And then using it onChange of the field as :
<Field
          name = "BusinessPhone"
          label = 'Business Phone'
          value={this.state.businessPhone}
          autoFocus={true}
          onChange = {(event,text) => { this.setState({ businessPhone: text });this.numberFormat(text) }}
          keyboardType = {'numeric'}
          clearButtonMode={'while-editing'} 
        />

**Comment by Noitidart** [comment]
Thanks for sharing @himanshug16 - it is helpful, I actually created my own material text field. Its not as great as this one, but I had to do it. :(

**Comment by AlbertoLopSie** [comment]
Hi @Noitidart !   Would you share it?

**Comment by Noitidart** [comment]
@AlbertoLopSie it's really bad, it's very limited. Embarssing to share. Excuse that please.

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. I've implemented `formatText` prop and now input masking is supported by this component (not released to npm yet).
