### ISSUE TITLE
Is Autocapitalize supported?

### ISSUE THREAD

**Issue by ospfranco** [n4kz/react-native-material-textfield#101]
React native text input supports auto capitalize prop, I'm trying to pass it to material textfield, but doesn't appear to be working.

https://facebook.github.io/react-native/docs/textinput.html#autocapitalize

**Comment by Noitidart** [comment]
Yes it works for me. I tested on Android.

**Comment by leonardoarruda** [comment]
Hi. My client have a very big database and all users have upper case login.  I need to use the Autocapitalize attribute to set every character to upper case, but it is not working. Right now, I could convert the string to uppercase before sending to server side. Help me please. Thanks.

**Comment by fabiorbap** [comment]
It's not working for me in Android, although it works on iOS
