### ISSUE TITLE
Cannot align two TextFields horizontally

### ISSUE THREAD

**Issue by Azeez09** [n4kz/react-native-material-textfield#104]
I have tried aligning two TextField elements horizontally by wrapping them in a View element using FlexBox, but ended up with the empty space, the child elements are not displayed, but place is occupied by view with empty space.

**Comment by igor90007** [comment]
me too.

**Comment by Azeez09** [comment]
As far as I understood the internal code for TextField component, it may not be possible to align them. As a work around, I have added a TextField inside a View component, and aligned the views horizontally using flex box concept. In other words, to align two TextFields, wrap each TextField in a separate View and try to align those two views by wrapping them in another View with flexbox style properties.

**Comment by Azeez09** [comment]
Closing this issue, because there is a workaround. But it would be great, if the material textfield can accept a property which decides whether it is an inline or block element.
