### ISSUE TITLE
Library dosen't support for only number type input

### ISSUE THREAD

**Issue by pawarn** [n4kz/react-native-material-textfield#107]
I want to get an only mobile number as an input in my application. This library always opens alphanumeric keyboard.

It is great if it only opens the number type keypad like android.

InputType = "number"

**Comment by fliPmitKlammern** [comment]
You can use _keyboardType_ for that: [](https://facebook.github.io/react-native/docs/textinput.html#keyboardtype)

> Other TextInput properties will also work
[](https://github.com/n4kz/react-native-material-textfield#properties)
