### ISSUE TITLE
Enhancements proposal

### ISSUE THREAD

**Issue by RUIFERNANDE5** [n4kz/react-native-material-textfield#11]
Hello and thank you for sharing this component.
Its probably the most stable floating-label type Input out there. 
Would be good if defaultValue would be implemented instead of value just to keep the default pattern.

Is it possible to change de label (after animating) fontSize? Couldn't find any reference in either the code or the docs.

And since you let us define disabled , there should be disabledStyle. 
Container styles would also be appreciated. Since you define the paddingTop per example, and In my use case it was just too much.
Just a couple enhancements. I can probably make a pr in the future if you don't have the time

**Comment by n4kz** [comment]
Hi! Thanks for your feedback, glad to see that my work is useful.

Will fix `defaultValue` in next release. Label font size and other styles are based on material design guidelines. I'm planning to implement dense text fields in the near future. Will also take a look what can be done for custom styles.

**Comment by n4kz** [comment]
Implemented `defaultValue` prop, released in `0.5.0`. Will close this issue for now and comment later, when done with label font size and styling.
