### ISSUE TITLE
Caret/ cursor won't hide on Android

### ISSUE THREAD

**Issue by kr4ckhe4d** [n4kz/react-native-material-textfield#111]
Devices: Samsung devices on Android 5 
Steps to reproduce:

1. Type in some text
2. Tap on TextField to display the Caret
3. Type in some text
4. Tap on the text field again to display the Caret
5. Repeat

**Samsung Galaxy J2 - 5.1.1**
![screenshot_2018-03-30-12-00-56](https://user-images.githubusercontent.com/12188189/38127262-07258c52-3413-11e8-9560-023381ce1efe.png)
**Samsung Galaxy Tab J - 5.1.1**
![screenshot_2018-03-30-12-04-33](https://user-images.githubusercontent.com/12188189/38127263-075b4d60-3413-11e8-8981-e43293e9a8da.png)

**Comment by jjercx** [comment]
+1

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. Please, take a look at recent release `0.13.0`. If problem still exists please let me know by updating this issue or creating a new one.
