### ISSUE TITLE
What is renderAccessory? I dont udnerstand it

### ISSUE THREAD

**Issue by Noitidart** [n4kz/react-native-material-textfield#113]
Hi there,
I'm on Android, may you please explain what renderAccessory is. I don't understand it from the readme.

**Comment by himanshug16** [comment]
hello @Noitidart , renderAccessory is basically a prop to use an icon or something similar to that with your textfield.In my case, i wanted a show/hide password icon with the field so i used it as:

renderAccessory={() => 
</TouchableOpacity>
<Icon name="eye" size={16} color='white'/>
</TouchableOpacity>
 }
You can also play around and can render it on certain conditions.
Hope it helps.

**Comment by Noitidart** [comment]
Ohh thank you @himanshug16 !
