### ISSUE TITLE
Null value causes crash

### ISSUE THREAD

**Issue by petrogad** [n4kz/react-native-material-textfield#115]
If we had a null value passed into the field's value, we end up throwing.

PR Submitted in #114

![screen shot 2018-04-18 at 2 02 20 pm](https://user-images.githubusercontent.com/2163698/38953400-3cd2e272-4314-11e8-8ec7-f0fbd57d5f9c.png)
![screen shot 2018-04-18 at 2 02 28 pm](https://user-images.githubusercontent.com/2163698/38953404-3e921506-4314-11e8-8d87-3121f4a406ea.png)

**Comment by petrogad** [comment]
You can reproduce this by doing:

```
<TextField value={null} />
```

**Comment by n4kz** [comment]
Fixed in 44930675.
