### ISSUE TITLE
Error Text Style

### ISSUE THREAD

**Issue by kamiloc** [n4kz/react-native-material-textfield#117]
It's possible to add style to the error text ?, i don't found the way and edit `~/react-native-material-textfield/src/components/field/index.js` like:

 ```
let errorStyle = {
      color: errorColor,

      opacity: focus.interpolate({
        inputRange: [-1, 0, 1],
        outputRange: [1, 0, 0],
      }),

      fontSize: title?
        titleFontSize:
        focus.interpolate({
          inputRange:  [-1, 0, 1],
          outputRange: [titleFontSize, 0, 0],
        }),
      fontFamily: **myFontFamily**
    };
```

I think it will be a good idea adding a prop to the component with errorTextStyle.

**Comment by ryachza** [comment]
I hit this issue as well - I wanted to title to be large, but it didn't make sense to have the error message that large as well (I also wanted different fonts, but I could have compromised on that).

This was the patch I used - I added `error...` properties and used those for the counter component as well:
[react-native-material-textfield+0.12.0.patch.zip](https://github.com/n4kz/react-native-material-textfield/files/1992124/react-native-material-textfield.0.12.0.patch.zip)

**Comment by guopeng1994** [comment]
+1

**Comment by ospfranco** [comment]
+1

I have found no way to customize the fontFamily on the error.

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. You can use `titleTextStyle` prop to set `fontFamily` and other styles for title, error message and counter.
