### ISSUE TITLE
prop-types as devDepednency?

### ISSUE THREAD

**Issue by Noitidart** [n4kz/react-native-material-textfield#118]
So I was having problems building. For the longest time. I would get this error:

> error: bundling failed: Error: Unable to resolve module `prop-types` from `C:\Users\x1\Documents\GitHub\Trusted-Score-Mobile\node_modules\react-native\Libraries\Components\ActivityIndicator\ActivityIndicator.js`: Module `prop-types` does not exist in the Haste module map

When it was tryign to bundle.

Finally I figured out i had to `npm i prop-types` because it is in the "dependencies". Should we maybe move it to "devDependencies"?

This was explained here - https://github.com/facebook/react-native/issues/14302#issuecomment-305946691

I'm just not sure. Do PropTypes stuff get stripped out in bundle procedure for production?

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. Is this still happening in recent RN versions? Please let me know if problem is still there by commenting here or creating a new issue.
