### ISSUE TITLE
Is this being maintained?

### ISSUE THREAD

**Issue by petrogad** [n4kz/react-native-material-textfield#119]
Is anyone actively maintaining this? Otherwise I'd be happy to pick it up, otherwise I'll fork it and work based off that.

we have a handful of PR's that should get merged to continue this forward.

Thank you!

**Comment by petrogad** [comment]
@n4kz Can you please help here?

I'd be happy to help out. Just let me know.

**Comment by petrogad** [comment]
Until this starts being maintained, forked and published the package to continue to update it based on PR's against this repo.

https://www.npmjs.com/package/react-native-materialui-textfield

**Comment by n4kz** [comment]
Answered in #149.
