### ISSUE TITLE
fontFamily dosn't work again.

### ISSUE THREAD

**Issue by igor90007** [n4kz/react-native-material-textfield#121]
in native TextInput fontFamily supports well. But in TextField doesn't.

**Comment by eAAwan** [comment]
@igor90007 I also face the same issue.
did you find any workaround?

**Comment by muzammil-triffort** [comment]
@eAAwan did you find any solution?

**Comment by eAAwan** [comment]
@muzammil-triffort yes pass font family in style prop of text input. ☺️

**Comment by r-anjirabi** [comment]
this works fine:
<TextField
    label ='type number...'
    labelTextStyle = {{fontFamily: "Consolas"}}
    style={{fontFamily: "Consolas"}}
  />
