### ISSUE TITLE
The animation in laggy.

### ISSUE THREAD

**Issue by SurajMDurgad** [n4kz/react-native-material-textfield#123]
```
<View style={styles.eachRow}>
	<TextField
		label='Password'
	        labelHeight={normalize(14)}
		fontSize={normalize(14)}
		value={this.state.password}
		style={styles.textFieldStyle}
		textColor={'#444444'}
		tintColor={'#BBBBBB'}
		baseColor={'#BBBBBB'}
		lineWidth={normalize(2)}
		inputContainerStyle={{ height: normalize(43) }}
		containerStyle={{flex: 1, paddingLeft: normalize(30),paddingRight: normalize(30), 
                                             paddingTop: normalize(10)}}
		labelFontSize={normalize(11)}
		secureTextEntry={true}
		onChangeText={ (password) => {this.setState({ password })} }
		labelTextStyle={{fontFamily: Platform.OS === 'ios' ? 'Montserrat-Medium' : 
                 'montserrat_medium',}}	/>
</View>
```

Above is the code I've used. When I click on the TextField it takes at least 5 seconds to complete the label animation and it is jittery. What might be the issue?

**Comment by vedadeepta** [comment]
I am facing this issue too any update on this. I'm running on android device.
RN-version : 0.55.4
react-native-material-textfield: 0.12.0

**Comment by SurajMDurgad** [comment]
Nope, I couldn't figure out any solution for that. I ended up removing the animation. And making the labels static.

**Comment by FinnGu** [comment]
Still no update on this issue?

**Comment by balthazar** [comment]
I think #88 intents to solve this, maybe you should go 👍 this one, although apparently there is [one issue](https://github.com/n4kz/react-native-material-textfield/pull/93#issuecomment-361921943) left from #93.

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. Please, take a look at recent release `0.13.0`. If problem still exists please let me know by updating this issue or creating a new one.
