### ISSUE TITLE
Copy and paste

### ISSUE THREAD

**Issue by jrrcdev** [n4kz/react-native-material-textfield#124]
Why I can't copy and paste in this input?

`<View>
              <TextField
                label="Address"
                placeholder="Enter the address which will receive"
                value={address}
                onChangeText={address => this.setState({ address })}
                error={addressError}
                returnKeyType="next"
                inputContainerStyle={{ paddingRight: 35 }}
                maxLength={95}
              />
              <IconMC
                style={{ position: "absolute", bottom: 12, right: 5 }}
                name="qrcode-scan"
                size={25}
                onPress={this.handleBarCodePressed.bind(this)}
              />
            </View>`

This one works:

`<View style={{ flex: 2 }}>
        <TextField
          label="Email"
          value={email}
          onChangeText={email => this.setState({ email })}
          keyboardType="email-address"
          error={emailError}
        />
        <TextField
          label="Password"
          value={password}
          onChangeText={password => this.setState({ password })}
          error={passwordError}
          secureTextEntry
        />
      </View>`

**Comment by ibnekhan** [comment]
> Looks like it do not work insite a Tab Navigator from react-navigation, but works on Stack Navigator.
> 
> The original TextInput works in both.
> 
> I'm using the version: 0.12.0

Any working solution for Tabs Navigator??

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. Please, take a look at recent release `0.14.0`. If problem still exists please let me know by updating this issue or creating a new one.

**Comment by Demuzx** [comment]
Why issue is closed? Bug still is in all versions, and in 0.14.x

**Comment by Walker0125** [comment]
still facing this problem
