### ISSUE TITLE
Expand scrollview when text grows

### ISSUE THREAD

**Issue by matteodanelli** [n4kz/react-native-material-textfield#125]
Hi,

I've set a multiline textfield and I have the following problem.
When I put too many lines the scollview which contains it doesn't resize or scroll properly; so, if I have two text field one below the other then the multiline will overlap the second one when text has too many lines (four, five and more).

Any help? Is the problem related to scrollview? Any other with the same issue?

**Comment by krakz999** [comment]
For me setting an object (even an empty object) as value for contentContainerStyle prop of scrollView solved the problem.

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. Please, take a look at recent release `0.13.0`. If problem still exists please let me know by updating this issue or creating a new one.
