### ISSUE TITLE
Not able to run example

### ISSUE THREAD

**Issue by witalobenicio** [n4kz/react-native-material-textfield#129]
I try to run the example app but the module isn't able to find neither react or react-native.
`Unable to load module 'react' from <directory>/components/field/index.js: Module does not exist in the module map`

**Comment by Bruno-Furtado** [comment]
+1

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. Please, take a look at recent release `0.13.0`. If problem still exists please let me know by updating this issue or creating a new one.
