### ISSUE TITLE
onContentSizeChange event isn't propagated to handler

### ISSUE THREAD

**Issue by nargov** [n4kz/react-native-material-textfield#13]
In an effort to scroll a field into view when it grows, I wanted to use the onContentSizeChange event.
It seems it is not called from the event handler within the code:

```javascript
onContentSizeChange({ nativeEvent }) {
    let { fontSize } = this.props;
    let { height } = nativeEvent.contentSize;

    this.setState({ height: Math.max(fontSize * 1.5, Math.ceil(height)) });
  }
```
Whereas in other events the handler is called like this:

```javascript
onChangeText(text) {
    let { onChangeText } = this.props;

    if ('function' === typeof onChangeText) {
      onChangeText(text);
    }
   ...
}
```
I wouldn't mind adding the missing lines and add a couple of tests. PR?

**Comment by n4kz** [comment]
Thanks for reporting, released fix in `0.5.1`
