### ISSUE TITLE
Not able to run this code successfully...

### ISSUE THREAD

**Issue by manojkraftly** [n4kz/react-native-material-textfield#133]
Please check this attached screenshot....
![simulator screen shot - iphone 6 - 2018-06-28 at 11 03 05](https://user-images.githubusercontent.com/36626338/42015060-45fcf518-7ac3-11e8-97bc-08c8d41e0903.png)

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. Please, take a look at recent release `0.13.0`. If problem still exists please let me know by updating this issue or creating a new one.
