### ISSUE TITLE
Do not Support multi line helper message. 

### ISSUE THREAD

**Issue by mufaawan** [n4kz/react-native-material-textfield#134]
Creating this issue so I can contribute to module by adding mentioned feature.

**Comment by redbugmilk** [comment]
Hi,

At this moment, I have this same issue on my project, the helper text gets truncated. If you want I can contribute to solution to agilize the process.

Thanks

**Comment by matteodanelli** [comment]
Same issue here! Anyone with a solution!?

**Comment by petrogad** [comment]
Solution for this has bee solved! 

Thanks @redbugmilk !

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. I've released multiline error message support in `0.14.0`.
