### ISSUE TITLE
how do we enable the character counter please

### ISSUE THREAD

**Issue by ekumahost** [n4kz/react-native-material-textfield#142]
how do we enable the character counter please, been looking at the doc no idea

**Comment by andrewmarmion** [comment]
Add the following property to your TextField like this:

```
<TextField
  ...
  characterRestriction={10}
  ...
/>
```

This will give you the character counter with 10 characters. You can see it referenced in the properties section of the readme. 
[https://github.com/n4kz/react-native-material-textfield#properties](https://github.com/n4kz/react-native-material-textfield#properties)
