### ISSUE TITLE
Does this script have the password input feature too..?

### ISSUE THREAD

**Issue by ekumahost** [n4kz/react-native-material-textfield#143]
Does this script have the password input feature too..?
https://www.npmjs.com/package/react-native-hide-show-password-input

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. Please take a look at [example](https://github.com/n4kz/react-native-material-textfield/blob/master/example/app.js#L215) project for implementation details (`secureTextEntry` and `renderRightAccessory` props).
