### ISSUE TITLE
Textfield not rendering properly

### ISSUE THREAD

**Issue by jrdn91** [n4kz/react-native-material-textfield#144]
I can't get this input to render properly, it doesn't look like a material input and typing content into the input doesn't work either.

Here is a screenshot of what I am seeing

![img_2f766d1577ae-1](https://user-images.githubusercontent.com/1076459/44226977-82030080-a15f-11e8-99cb-29848fc9fbb1.jpeg)

When I type it looks like this

![img_dadc1835f6ca-1](https://user-images.githubusercontent.com/1076459/44227038-a8c13700-a15f-11e8-88bd-00a8ac723e83.jpeg)

I follwed the code in the setup guide

```
export default class Login extends React.Component {
  state = {
    phone: '',
    password: ''
  };
  render() {
    let { phone, password } = this.state;
    return (
      <View style={styles.container}>
        <TextField
          label='Phone number'
          value={phone}
          onChangeText={ (phone) => this.setState({ phone }) }
        />
        <TextField
          label='Password'
          value={password}
          secureTextEntry
          onChangeText={ (password) => this.setState({ password }) }
        />
      </View>
    );
  }
}
```

I'm definitely getting the input value in the `onChangeText` function callback but it's just not displaying anything. I also receive no errors

I'm on
Node v8.0.0
NPM v6.4.0
React v16.3.1
React-Native v0.55.4
Latest version of this component

**Comment by wesleyguirra** [comment]
How do you solve this?

**Comment by Pelikhov** [comment]
@wesleyguirra Just add width in containerStyle property.

`
<TextField
  // ... some your properties
   containerStyle={{ width: 'you width value' }}
 />
`
