### ISSUE TITLE
Does this support 'Outlined' textfield variant?

### ISSUE THREAD

**Issue by shehang** [n4kz/react-native-material-textfield#148]
Hi,

Does this library support 'Outlined' material textfield variant? I'm asking because I couldn't find a prop or I didn't see an example relevant to it.

https://material.io/design/components/text-fields.html#outlined-text-field

Thank in advance.

**Comment by RenalPraba** [comment]
I created a class component from this library to create material outlined text variant, if you want i want share it with a purpose

**Comment by alburdette619** [comment]
I have the same requirement @shehang . Did you find a solution?

**Comment by jainkunal40** [comment]
I have the same requirement, did anyone find a solution, or any other suggestion?

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. Its not supported yet, but I have a plan to implement this in near future.

**Comment by n4kz** [comment]
Implemented filled and outlined variants and released to npm in `0.16.1`.

**Comment by mubark75** [comment]
@n4kz can u show us an example of using it, ican't find variant props

**Comment by n4kz** [comment]
Yep,

```
import { OutlinedTextField } from 'react-native-material-textfield';
```

And that is it.
