### ISSUE TITLE
Maintainer? 

### ISSUE THREAD

**Issue by petrogad** [n4kz/react-native-material-textfield#149]
I, along with others, have loved this product however need to see a handful of updates made.  

Until the point where our maintainer returns, I've forked and updated this project with a handful of the pull requests which have been requested.

Whenever the maintainer returns, I'll happily issue a pull request against this project with all the updates so we can continue working based off it. 

Can follow here:
https://www.npmjs.com/package/react-native-materialui-textfield

**Comment by n4kz** [comment]
Thanks for your efforts and sorry for not being able to maintain this component for a long time. I'll try to do my best and bring it back to life in next few days.
