### ISSUE TITLE
Keyboard is hides the input view when the component is at the bottom of the screen

### ISSUE THREAD

**Issue by cheong12001** [n4kz/react-native-material-textfield#159]
Keyboard is hides the input view when the component is at the bottom of the screen, can somebody tell me how to avoid this problem. using react native expo for development. Thanks in advanced

**Comment by OlegPanfyorov** [comment]
Same sheet

**Comment by KandariSrinivas** [comment]
wrap the input's container into KeyboardAwareScrollView and give value to extraHeight prop,this should  help
