### ISSUE TITLE
Displayed value doesn't change when filtering input

### ISSUE THREAD

**Issue by Strayer** [n4kz/react-native-material-textfield#16]
I have a TextField that should only allow numeric characters. For this I implemented a onChange-callback that filters everything except 0-9 and sets it to state.

```js
class SomeComponent extends React.Component {
    onChange = (value) => {
        this.setState({ value: value.replace(/[^0-9]+/, "") })
    }

    render() {
        return <TextField value={this.state.value} onChangeText={this.onChange} />;
    }
}
```

When the filtered value is the same as the initial value, the TextField won't update the displayed text.

1. initial state of SomeComponent: { value: "1970" }
2. user enters: 1970aaa
3. state of SomeComponent stays on { value: "1970" }
4. (expected) TextField is re-rendered with "1970" as its text (this works with RNs TextInput)

Actual behaviour: TextField still shows "1970aaa", only when the user enters another number the actual current state will be displayed.

**Comment by n4kz** [comment]
Thanks for reporting, fixed by reordering `setState` and `onTextChange` calls in 7a63aed, released in `0.5.4`.
