### ISSUE TITLE
not helpful in flexDirection:'row'

### ISSUE THREAD

**Issue by harryharihar** [n4kz/react-native-material-textfield#162]

**Comment by kpaulus1997** [comment]
I run in the same problem today, if you try to place an item next to the text input it gets pushed below the text input even though I've wrapped it in a container with flexDirection: 'row', my workaround for the moment is to apply a position: 'absolute' to the containerStyle

**Comment by kpaulus1997** [comment]
For everyone having the same issue, use this:

`<View style={{ height: 72 }}>
    <TextField
         containerStyle={{ position: 'absolute', top: 0, bottom: 0, left: 0, right: 0 }}
    />
</View>`

**Comment by harryharihar** [comment]
you solved my all problem

**Comment by kpaulus1997** [comment]
You're welcome
