### ISSUE TITLE
Update Example project

### ISSUE THREAD

**Issue by lunvjp** [n4kz/react-native-material-textfield#163]
>Although string refs are not deprecated, they are considered legacy, and will likely be deprecated at some point in the future. Callback refs are preferred.

Detail: [https://zhenyong.github.io/react/docs/more-about-refs.html](HERE)
* Let's use this to update your Example I think
Thanks.

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. Example project now uses callbacks and I will update it to `React.createRef()` at some point in future.
