### ISSUE TITLE
How to set InlineImage for textfield [image to left in textfield] for both android & iOS

### ISSUE THREAD

**Issue by sangeethkumarv** [n4kz/react-native-material-textfield#168]
![Screenshot 2019-04-16 at 10 16 47 AM](https://user-images.githubusercontent.com/42767283/56182647-c2898580-6030-11e9-872b-61b71ef477f4.png)

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. It will be possible to use `renderLeftAccessory` prop to render image or anything else on the left side starting from next release.
