### ISSUE TITLE
Bundling Failed with bundling failed: Error: ENOENT: no such file or directory, scandir 

### ISSUE THREAD

**Issue by imbudhiraja** [n4kz/react-native-material-textfield#170]
Facing issue after installing the latest version of the package. 
Dependencies 
1. React-native - 0.59.4
2. React-native-material-textfield -  0.12.0

**Comment by sternetj** [comment]
I am also having this issue. Did you figure out how to fix it?

**Comment by bruscantini** [comment]
I'm also having this issue. I'm trying to upgrade expo sdk. It can't find
`node_modules/react-native-material-textfield/src/components/field/node_modules/react-native'`

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. Please, take a look at recent release `0.13.0`. If problem still exists please let me know by updating this issue or creating a new one.

**Comment by bruscantini** [comment]
@n4kz Works! Thanks
