### ISSUE TITLE
how to change placeholder font size 

### ISSUE THREAD

**Issue by elirangoshen** [n4kz/react-native-material-textfield#174]
I tried to use  fontSize in style , labelStyle and labelTextStyle props but all of them have effect only on when it's focused, while id like to change the font size when it shows the placeholder. 

can you sugest how i can do it ?

**Comment by jitenderchand** [comment]
You can use `fontSize={20}` as a props .

```
<TextField
    labelFontSize={20}
    fontSize={20}
    inputContainerStyle={styles.inputContainerStyle}
    label="Price"
    inputStyle={styles.inputStyle}
    containerStyle={styles.containerStyle}
    tintColor={theme.palette.PRIMARY}
    style={styles.inputColor}
    value={price}
    onChangeText={value =>
     this.handleNumericInput('price', value)
    }
    maxLength={3}
   />
```

**Comment by Mojtaba-Pourkhanlar** [comment]
### **mui v5 change placeholder font size.**

<TextField
onChange={(e) => ......}
placeholder={"demo"}
sx={{"& input::placeholder": { fontSize: "13px"},}}
/>
