### ISSUE TITLE
disabledLineType not working.

### ISSUE THREAD

**Issue by Hashir524** [n4kz/react-native-material-textfield#176]
It always gives you a solid line, no matter what value i am giving.

**Comment by whalemare** [comment]
Can remove line for disabled type, for example
```
      <TextField
        disabled={true}
        disabledLineWidth={0}
      />
```

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. Please, take a look at recent release `0.13.0`. If problem still exists please let me know by updating this issue or creating a new one.
