### ISSUE TITLE
Warnings about componentWillUpdate, componentWillReceiveProps

### ISSUE THREAD

**Issue by HasnainSomroBuzzInteractive** [n4kz/react-native-material-textfield#177]
Hi!
First off I really like your work. Amazing.
Are you going to update this library or not. Because it gives a lot of warnings. If you are not going to update, clearly write it. So we should use it as a local module and fix these warnings.

<img width="378" alt="Screenshot 2019-08-29 at 7 23 49 PM" src="https://user-images.githubusercontent.com/52532546/63948757-a55ecc00-ca92-11e9-8b8f-04863041f937.png">
<img width="366" alt="Screenshot 2019-08-29 at 7 24 15 PM" src="https://user-images.githubusercontent.com/52532546/63948769-ad1e7080-ca92-11e9-8599-029bd1639e39.png">

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. Fixed in 07f3fb8 and 99d1178. I'll try to make a new release as speed as possible.
