### ISSUE TITLE
Is it possible to change the label's starting position?

### ISSUE THREAD

**Issue by nhuesmann** [n4kz/react-native-material-textfield#180]
Rather than having the label move from the bottom of the box to the top, is it possible to have the label start in the middle then move to the top? I want to keep the actual text input where it is so that when text is entered the label floats and the entered text is below the middle. I've poked around with a number of different settings but couldn't figure out how to do this or if it's possible.

**Comment by Abddullah** [comment]
same problem how to start label from right side i am using Arabic language but label start from left side

**Comment by anfriis** [comment]
I have exactly the same issue as @nhuesmann. Did you find a solution?

**Comment by nhuesmann** [comment]
Yes, I had to clone the codebase and edit a few lines of code. It was a few weeks ago so I don't completely remember, but looking through the code right now I believe I changed:
- [components/label/index.js, line 74](https://github.com/n4kz/react-native-material-textfield/blob/d1ee23e77083227f569af70ecf6f43063d36ad3d/src/components/label/index.js#L74)
- Changed it to `baseSize + fontSize * 0.25 - 12`
- [components/field/styles.js, line 49](https://github.com/n4kz/react-native-material-textfield/blob/d1ee23e77083227f569af70ecf6f43063d36ad3d/src/components/field/styles.js#L49)
- Changed it to `top: -9`

Since having made those changes, this library has been updated. I'm not sure if the lib updates invalidate what I did, so if you try my changes and they don't work, I could prob just fork the lib and make the changes on the fork. Let me know if these changes work, you might have to tweak the numbers slightly depending on font size and font family.

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. By default label is positioned to precisely match position of input text. However it's possible to do something like `labelTextStyle={{ transform: [{ translateY: -12 }] }} to move it higher.

**Comment by anfriis** [comment]
@n4kz I was able to make it work after upgrading to version 0.15.0 and using `contentInset` and `translateY` as you suggested 🥇 

I am using TypeScript and types have not been updated for version 0.15.0, so I create this [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39235) to update them.

**Comment by n4kz** [comment]
Please take a look at new `labelOffset` prop. Now it's possible to fine tune starting and final position of label animation. I'll release it to npm later this week.

**Comment by anfriis** [comment]
Sounds awesome!
