### ISSUE TITLE
Layout broken if not used inside a ScrollView

### ISSUE THREAD

**Issue by davidef** [n4kz/react-native-material-textfield#185]
We are trying to build a login form using TextField.
Username and password TextField are not wrapper inside a ScrollView but centered in a View.
You can easily reproduce the issue by replacing the ScrollView in the example with a View and you get this
![Screenshot_1571143759](https://user-images.githubusercontent.com/967588/66832854-00715300-ef5b-11e9-90b2-cdc554df9ba3.png).
with TextField without height.

**Comment by yedu890** [comment]
Same issue here

**Comment by n4kz** [comment]
Thanks for issue! I've left `flex: 1` on input container :( Fixed in 6724993. I'll release it in `0.14.1` later today.
