### ISSUE TITLE
Vertical line appears on the left side of the input field

### ISSUE THREAD

**Issue by yedu890** [n4kz/react-native-material-textfield#186]
The issue is there is a vertical line appears on the left side of the input field. This is only in Android 7 (Nougat). Please help
![WhatsApp Image 2019-10-15 at 6 39 38 PM](https://user-images.githubusercontent.com/56593520/66834433-345c7080-ef7b-11e9-9ecf-5978c1e190e4.jpeg)

**Comment by n4kz** [comment]
Thanks for issue! Please, check `0.14.1`, should be okay now.
