### ISSUE TITLE
How to add DropDown icon on right side on TextInput 

### ISSUE THREAD

**Issue by vnanaware** [n4kz/react-native-material-textfield#187]
![Simulator Screen Shot - iPhone X - 2019-10-17 at 13 11 53](https://user-images.githubusercontent.com/16416191/66988501-43106800-f0e0-11e9-8fb1-4c46e07b2de4.png)

**Comment by n4kz** [comment]
Thanks for question. You can use `renderRightAccessory` callback to render anything you want on the right side of label. Also I have a component [react-native-material-dropdown](https://github.com/n4kz/react-native-material-dropdown) based on this `TextField`, but it's slightly out of date now.
