### ISSUE TITLE
renderRightAccessory and label active position

### ISSUE THREAD

**Issue by chriskaya** [n4kz/react-native-material-textfield#189]
Hello,

Right now the label only move vertically when the field is focused. But when using renderRightAccessory, it does not seem right to me :  

![Screenshot_20191018-171848](https://user-images.githubusercontent.com/4079132/67107413-b8f1fd80-f1cc-11e9-855b-45d7bd666097.png)

How could I make it translate horizontally to the start of the field ?

Thank you for your help :)

**Comment by n4kz** [comment]
Thanks for question. Existing behaviour matches material design guidelines. I see no easy way to adjust active label position now, but I'll take a closer look for possible solutions.

**Comment by chriskaya** [comment]
Thank you for your answer :)
I don't have time right now (in a middle of a rush), but I'll try to find a way myself and create a PR if I succeed :)
BTW, thanks a lot for this lib, it's **really** good! :)

**Comment by n4kz** [comment]
Thanks for your feedback! I've implemented `labelOffset` prop and now it's possible to adjust initial and final label positions independently. I'll release it to npm later this week.
