### ISSUE TITLE
TextField with a different behavior than TextInput

### ISSUE THREAD

**Issue by brunojs02** [n4kz/react-native-material-textfield#190]
With the following code, I'm getting different behaviours, when i use TextInput component with empty value, when i type something, the component keep with initial value, because the component wasn't re-render, but with TextField I can keep typing without lost what i typed before.
```
// App.js
import React from 'react';
import { View, TextInput } from 'react-native';
import { TextField } from 'react-native-material-textfield';

const App = () => (
  <View style={{ flex: 1, padding: 16, backgroundColor: '#fff' }}>
    <TextField
      value=""
      label="Label"
    />
    <View style={{ borderBottomWidth: 1 }}>
      <TextInput placeholder="Placeholder" value="" />
    </View>
  </View>
);

export default App;
```
![textfield](https://user-images.githubusercontent.com/7714813/67308603-c19a4a80-f4d0-11e9-9dbe-63b8d90f1d84.gif)

**Comment by n4kz** [comment]
Thanks for issue. `TextField` now is fully uncontrolled component to prevent glitches and achieve smooth animation. However `TextInput` is fully controlled.
