### ISSUE TITLE
why was the value prop removed?

### ISSUE THREAD

**Issue by idanlo** [n4kz/react-native-material-textfield#193]
I am doing some formatting for the user input in my application using this package and I noticed since the last update the formatting doesn't show and it is only the text that the user inputs.

I assume this is why you added the `formatText` function? Isn't it better to take the value from the props?

**Comment by n4kz** [comment]
Thanks for question! `TextField` is now fully uncontrolled component with instance method `setValue` for forced updates. `value` prop was not removed, however it's more like initial value now. Uncontrolled behaviour was chosen over controlled to eliminate glitches and improve animation.

You're right about `formatText`, please use it to implement input masking.
