### ISSUE TITLE
Error, if component has onChangeText property

### ISSUE THREAD

**Issue by agat** [n4kz/react-native-material-textfield#2]
This code generate a error `value is not defined`:

````js
<TextInput
    label={'Email'}
    keyboardType="email-address"
    value={email}
    onChangeText={this.updateEmail}
/>
````

I think problem is here https://github.com/n4kz/react-native-material-textfield/blob/master/src/components/field/index.js#L134, need change `value` to `this.value()`.

Thanks for component!

**Comment by n4kz** [comment]
Thanks for reporting, fixed in 0.1.1.
