### ISSUE TITLE
Textfield hiding last word when unfocused

### ISSUE THREAD

**Issue by joan-domingo** [n4kz/react-native-material-textfield#201]
RN 0.61.2
react-native-material-textfield: 0.16.1
Platform: iOS (Android works fine)

When entering more than 1 word, and the last word doesn't fit inside the input container, it's not displayed when unfocused. See example:

**Focused TextField**
<img width="360" alt="Screenshot 2019-11-19 at 16 41 11" src="https://user-images.githubusercontent.com/6553060/69161450-7b460480-0aeb-11ea-8ab7-30b7be1170f9.png">

**Unfocused TextField**
<img width="364" alt="Screenshot 2019-11-19 at 16 41 19" src="https://user-images.githubusercontent.com/6553060/69161448-7b460480-0aeb-11ea-8406-3f101cb0546a.png">
 In this case the word 'BBB..' won't be displayed.

I would expect that the TextField would show as much text as possible even if the last word is not fully visible.

Anyone else had the same issue? Is there a workaround or maybe a way to fix it?

**Comment by Dr-Horv** [comment]
For me it worked by overriding the textAlign-property: `style={{ textAlign: 'auto' }}`
