### ISSUE TITLE
value is not set when getting sim card number

### ISSUE THREAD

**Issue by art1373** [n4kz/react-native-material-textfield#208]
I am using react-native-sim-data and with the regular textinput of react native it gets the value of sim number and set it to the text input value no problem.

with this package nothing is happening
`
  <TextInput value={phoneNum} onChangeText={this.getNum}/>
              {/* <OutlinedTextField
                label="شماره موبایل"
                keyboardType={'numeric'}
                textColor="#CD0448"
                maxLength={11}
                tintColor="#CD0448"
                errorColor="red"
                placeholder={phoneNum}
                labelTextStyle={{
                  fontFamily: 'IRANSansMobile',
                  paddingTop: hp(1.2),
                }}
                onChangeText={this.getNum}
                value={phoneNum}
              /> */}
`
the interesting thing is the placeholder changes but the value not!

**Comment by ajinkyadesai-git** [comment]
any solution?
value is not getting set when i pass prop, value={this.state.customerList}

Edit: Able to set through
1)ref={ref => { this.customerName = ref; }}
2)this.customerName.setValue( );

**Comment by vowar** [comment]
noticed that `value` prop is used as the initial value but after the input initialization does not affect input. are there some issues because of which we cannot use it as the controlled input?

**Comment by bb-cuongnv** [comment]
> I am using react-native-sim-data and with the regular textinput of react native it gets the value of sim number and set it to the text input value no problem.
> 
> with this package nothing is happening
> `<TextInput value={phoneNum} onChangeText={this.getNum}/> {/* <OutlinedTextField label="شماره موبایل" keyboardType={'numeric'} textColor="#CD0448" maxLength={11} tintColor="#CD0448" errorColor="red" placeholder={phoneNum} labelTextStyle={{ fontFamily: 'IRANSansMobile', paddingTop: hp(1.2), }} onChangeText={this.getNum} value={phoneNum} /> */}`
> the interesting thing is the placeholder changes but the value not!

I have the same problem. I downgraded from 0.16.1 to 0.12.0. It worked for me
I using React-native: 06.1.5

**Comment by jhonatanhrg** [comment]
change value to defaultValue

**Comment by art1373** [comment]
@jhonatanhrg  the default value worked Thanks.
