### ISSUE TITLE
Remove underline 

### ISSUE THREAD

**Issue by mahbubmukul** [n4kz/react-native-material-textfield#21]
I want to remove the underline of textfield.. (Red box marked in image). 
I tried with 'underlineColorAndroid' and 'tintColor' properties.

![screenshot_2017-07-05-14-17-08](https://user-images.githubusercontent.com/13809555/27855801-a3327be0-618d-11e7-8cfa-783749e11d4a.png)

**Comment by n4kz** [comment]
For this moment it's not possible, actual look and feel tends to match [material design guidelines](https://material.io/guidelines/components/text-fields.html), and I'm not planning to implement custom styling any time soon. Probably the best way to apply custom styles is to create a fork.

**Comment by lavarajallu** [comment]
I followed meterial Design But in this 
Bottom line

Thickness: 2dp
Masked by rounded corners of rectangle

How can i use in this please  give me suggetion

**Comment by farhanmeo** [comment]
Try this lineWidth={0} if you want to hide the default underline

and if you want to hide the line after which appears after click try this activeLineWidth={0}
