### ISSUE TITLE
renderRightAccessory/renderLeftAccessory not displaying icon.

### ISSUE THREAD

**Issue by avilesj** [n4kz/react-native-material-textfield#214]
Greetings,

I'm trying to make a wrapper for this component and I am (unsuccessfully) trying to display an icon using the renderLeft/RightAccessory prop.

I made sure the icon is displaying properly just returning it and it seems to work just fine, but when I pass it to this repository's component, it doesn't show on either side.

Is there anything I'm missing? I tried looking at the examples and it displays a component from `react-native-vector-icons` just returning it, as I'm doing right now.

I've tried resizing the input field and it's container because in the past I've been bitten by a lack of `flex` in the styles, among other things (stuff displaying outside the screen) just to be sure there's nothing off regarding its space within the screen.

Below is the code. 

Note: TextField is being imported _as_ MaterialTextField.

```
const TextField = ({ label, errorMessage }) => {
  const icon = () => (
    <View>
      <Image
        source={emptyPhoto}
        style={{
          height: 14,
          width: 14,
        }}
      />
    </View>
  );

  return (
    <MaterialTextField
      label={label}
      error={errorMessage}
      renderRightAccessory={icon}
      renderLeftAccessory={icon}
    />
  );
};
```

**Comment by Drzaln** [comment]
you must using CamelCase.
```const TextField = ({ label, errorMessage }) => {
  const Icon = () => {
   return (
    <View>
      <Image
        source={emptyPhoto}
        style={{
          height: 14,
          width: 14,
        }}
      />
    </View>
   )
  };

  return (
    <MaterialTextField
      label={label}
      error={errorMessage}
      renderRightAccessory={icon}
      renderLeftAccessory={icon}
    />
  );
};```

**Comment by avilesj** [comment]
This was a mistake by me, since we were using an old version (0.12). This was fixed afteer updating to the latest.
