### ISSUE TITLE
onChange breaks under RN 0.46

### ISSUE THREAD

**Issue by nargov** [n4kz/react-native-material-textfield#23]
The [RN 0.46.1 release notes](https://github.com/facebook/react-native/releases/tag/v0.46.1) state that the `contentSize` property was removed from the `onChange` event (and now `onContentSizeChange` is invoked when it is supposed to). This breaks [this event delegation](https://github.com/n4kz/react-native-material-textfield/blob/master/src/components/field/index.js#L208), since `contentSize` is null.

To continue supporting older versions of RN, a null check for `contentSize` in the same if statement should fix the issue.

**Comment by n4kz** [comment]
Thanks for reporting, solved by removing `onContentSizeChange` fix for RN 0.46 (fix is not needed anymore). Released in `0.6.3`.
