### ISSUE TITLE
Compatibility with RN v0.62.0

### ISSUE THREAD

**Issue by sajaddp** [n4kz/react-native-material-textfield#245]
Hi,
Does anyone confirm that `react-native-material-textfield` is compatible with the RN v0.62.0?

**Comment by reyn-nova** [comment]
I got property style undefined in this module,

All I need to do to make it work is

commenting ```style: Animated.Text.propTypes.style,``` on ```node_modules/react-native-material-textfield/src/components/label/index.js```

commenting ```style: Animated.Text.propTypes.style,``` on ```node_modules/react-native-material-textfield/src/components/affix/index.js```

commenting ```style: Animated.Text.propTypes.style,``` on ```node_modules/react-native-material-textfield/src/components/helper/index.js```

**Comment by sajaddp** [comment]
Dear @reynaldpn please check https://github.com/n4kz/react-native-material-textfield/issues/238#issuecomment-596026010
