### ISSUE TITLE
Value not update state

### ISSUE THREAD

**Issue by AwanBambang** [n4kz/react-native-material-textfield#247]
i have code like this
<MDInput is custom comp from <TextField>

![DimScreen_Nnp1evdMm0](https://user-images.githubusercontent.com/58282255/78116859-1a322400-742f-11ea-9218-e191e26c507d.png)

But resul is not what i expect

https://drive.google.com/file/d/1UaAqjhRze8UEMB-VQ7KTNMYTJz2ixzP2/view?usp=drivesdk

**Comment by vandero** [comment]
I have the exact same problem.

**Comment by rahulje9** [comment]
> i have code like this
> <MDInput is custom comp from
> 
> ![DimScreen_Nnp1evdMm0](https://user-images.githubusercontent.com/58282255/78116859-1a322400-742f-11ea-9218-e191e26c507d.png)
> 
> But resul is not what i expect
> 
> https://drive.google.com/file/d/1UaAqjhRze8UEMB-VQ7KTNMYTJz2ixzP2/view?usp=drivesdk

try version @0.12.0

**Comment by darleikroth** [comment]
Use the `defaultValue` prop instead

**Comment by AwanBambang** [comment]
> > i have code like this
> > <MDInput is custom comp from
> > ![DimScreen_Nnp1evdMm0](https://user-images.githubusercontent.com/58282255/78116859-1a322400-742f-11ea-9218-e191e26c507d.png)
> > But resul is not what i expect
> > https://drive.google.com/file/d/1UaAqjhRze8UEMB-VQ7KTNMYTJz2ixzP2/view?usp=drivesdk
> 
> try version @0.12.0

Thanks, You save my day
