### ISSUE TITLE
Touch area in TextView

### ISSUE THREAD

**Issue by felipeborba-dev** [n4kz/react-native-material-textfield#248]
The TextField touch area is considering an area outside the field, I have attached an example gif

![2](https://user-images.githubusercontent.com/50309174/78165181-52cb0100-7421-11ea-88f6-e8616733c907.gif)

**Comment by Dina-Nashaat** [comment]
possible duplicate of: https://github.com/n4kz/react-native-material-textfield/issues/199

**Comment by bbaoNg97** [comment]
may i know whats the solution for this ya?
i also encountered this issue

**Comment by gaurav-psych** [comment]
solution for this

**Comment by felipeborba-dev** [comment]
I'm not using this lib anymore, I migrated to react-native-paper

**Comment by felipeborba-dev** [comment]
This code can help

`labelTextStyle={{
position: 'absolute',
left: '100%'
}}`
