### ISSUE TITLE
I install it via yarn , it succeeded but when I import this material-textfield it occurs error. Here is some Screenshot

### ISSUE THREAD

**Issue by sefatanam** [n4kz/react-native-material-textfield#260]
![Screenshot_4](https://user-images.githubusercontent.com/37630292/80754561-0d4d4100-8b51-11ea-8926-79cea65b5a97.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/37630292/80754568-0f170480-8b51-11ea-9fae-e9663e30c8cb.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/37630292/80754572-10e0c800-8b51-11ea-96c5-e3146c330fce.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/37630292/80754577-11795e80-8b51-11ea-8e66-47b3f58878d5.jpg)

**Comment by Qcza** [comment]
It seems to not provide the .d.ts files with the package. You need to also make `yarn add -D @types/react-native-material-textfield`.

**Comment by sefatanam** [comment]
thank you, it's solved
