### ISSUE TITLE
WARN Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`

### ISSUE THREAD

**Issue by ezequiasaramburu** [n4kz/react-native-material-textfield#269]
Output when the input **TextField** changes from _**valid input**_ styles to _**error message**_ styles or the other way around:

_**WARN** Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`
in TextField (at FormInput.js:58)._

The workaround for me, was to add:  **_useNativeDriver: false_** on **src/app/components/field/index.js** on the **options** object of **startFocusAnimation** method.
It's setted to false, because style property 'borderColor' is not supported by native animated module, but it is required to be explicity set as the _**WARN**_ says.

**Comment by ealimardaniii** [comment]
on node_modules/react-native-material-textfield/src/app/components/field/index.js line 218 

change 

  startFocusAnimation() {
    let { focusAnimation } = this.state;
    let { animationDuration: duration } = this.props;

    let options = {
      toValue: this.focusState(),
      duration,
    };

    startAnimation(focusAnimation, options, this.onFocusAnimationEnd);
  }

to:

  startFocusAnimation() {
    let { focusAnimation } = this.state;
    let { animationDuration: duration } = this.props;

    let options = {
      toValue: this.focusState(),
      useNativeDriver:false,
      duration,
    };

    startAnimation(focusAnimation, options, this.onFocusAnimationEnd);
  }

this worked for me

**Comment by gabrieldonadel** [comment]
Hi @ezequiasaramburu, unfortunately this is a known bug in `react-native-material-textfield` and this lib appears to be abandoned. 
I suggest you using this fork [rn-material-ui-textfield](https://www.npmjs.com/package/rn-material-ui-textfield) that has fixed this and some other bugs. 

If you want to give it a try just run

```
npm install --save rn-material-ui-textfield
