### ISSUE TITLE
Not compatible with react native 0.42.0

### ISSUE THREAD

**Issue by 4ship** [n4kz/react-native-material-textfield#29]
I cloned the repository and changed the version of react native to this : 

"react": "15.4.1",
"react-native": "0.42.0",

I get this error 
undefined is not an object (evaluating "_reactnative.ViewPropTypes.style")

**Comment by n4kz** [comment]
Thanks for reporting, accessing `View.propTypes` is deprecated in recent RN versions and superseded by `ViewPropTypes`. Fixed in `0.6.5`.
