### ISSUE TITLE
Error, if component has empty string in error property :)

### ISSUE THREAD

**Issue by agat** [n4kz/react-native-material-textfield#3]
Example:

```jsx
<TextField
    label='Answer'
    value={'42'}
    error={''}
 />
```

Temp. fix is change from `''` to`null`.

**Comment by n4kz** [comment]
Thanks for reporting! Error was produced by weird JSX conditional rendering if `error`, `title` or `characterRestriction` had `''` or `0` values. Fixed in 0.2.5 :)
