### ISSUE TITLE
Free space on top of input; when label is small size

### ISSUE THREAD

**Issue by hosembafer** [n4kz/react-native-material-textfield#30]
Unknown padding top in every input, I think it's the reserved space for labels, but in many cases it's disturb.

**Comment by n4kz** [comment]
Padding is set according to material guidelines. I'll make it configurable in next release.

**Comment by hosembafer** [comment]
Thank you, that's what I need to be a happy.

**Comment by n4kz** [comment]
Released `0.7.0` with new props `labelHeight`, `labelPadding` and `titleFontSize`. For dense style from material design guidelines use `labelHeight={20}` and `labelPadding={0}`.

**Comment by hosembafer** [comment]
Yes, labelHeight fixes my problem.

**Comment by voidstarfire** [comment]
Doesn't seem to work anymore. Nothing happens.

My example:

```
<TextField 
    labelPadding={50}
    labelHeight={50}
/>
```

**Comment by n4kz** [comment]
@voidstarfire Please, provide additional info. Package version, RN version, platform and, if possible, minimal code sample.

**Comment by voidstarfire** [comment]
Thanks for your speedy reply. My bad I was using an older version.
Sorry for my idiocy.

**Comment by n4kz** [comment]
You are welcome :)
