### ISSUE TITLE
labelOffset not added to TypeScript definitions

### ISSUE THREAD

**Issue by bezenson** [n4kz/react-native-material-textfield#309]
1. Add `labelOffset` prop to component
2. Observe an issue with typescript

I can create a Pull Request, but I see that author not answering for a long time here

**Comment by gabrieldonadel** [comment]
> 1. Add `labelOffset` prop to component
> 2. Observe an issue with typescript
> 
> I can create a Pull Request, but I see that author not answering for a long time here

@inferusvv feel free to open a PR in this repo https://github.com/gabrieldonadel/rn-material-ui-textfield
