### ISSUE TITLE
onclick outside textfield

### ISSUE THREAD

**Issue by Thanmai-C** [n4kz/react-native-material-textfield#31]
Hi,

I wanted to know if there is any way to make the text field label fall back to its place when the user click anywhere else,other than on the next/other text fields (and also if nothing entered to it)

Similarly as when a click is done on the field the label goes up and falls down if nothing entered to it and next text field is clicked on. In the same manner,the label has to collapse down (when nothing is typed) and the user clicks on the screen some where else.

**Comment by n4kz** [comment]
By default focus is lost on taps outside of the textfield if textfield is in `ScrollView` component. For `ScrollView` default behaviour can be altered using [`keyboardShouldPersistTaps`](https://facebook.github.io/react-native/docs/scrollview.html#keyboardshouldpersisttaps) prop. Focus can be controlled manually using `.focus()` and `.blur()` methods on text field reference.

For code samples please take look at example app [source](https://github.com/n4kz/react-native-material-textfield/blob/master/example/app.js).

**Comment by egemon** [comment]
`keyboardShouldPersistTaps` doesn't work with this library. And I was not able to run this example that u provided as well.
