### ISSUE TITLE
Animated: `useNativeDriver` was not specified warning

### ISSUE THREAD

**Issue by bezenson** [n4kz/react-native-material-textfield#310]
> Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`

On latest React Native `useNativeDriver` parameter is necessary. Somewhere in library it is not added.

**Comment by gabrieldonadel** [comment]
> > Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`
> 
> On latest React Native `useNativeDriver` parameter is necessary. Somewhere in library it is not added.

I would suggest just using `rn-material-ui-textfield` as this lib has not received any updates for over a year 

```
npm install --save rn-material-ui-textfield
