### ISSUE TITLE
Support for custom font-family

### ISSUE THREAD

**Issue by gtRfnkN** [n4kz/react-native-material-textfield#32]
Thank you for this great library - we are using it in our App already and are very satisfied. 

One thing, that is kind of important for us, is the support of custom fonts. Would it be possible to add a `fontFamily` for the text views used in the TextField?

**Comment by patreu22** [comment]
+1

**Comment by gtRfnkN** [comment]
Maybe it would also be a good idea to add a custom style prop to the Text views like `containerStyle`?

**Comment by n4kz** [comment]
Thanks for your feedback!

Added new props `labelTextStyle`, `titleTextStyle` and `affixTextStyle`. Please note, `fontSize` should be set using dedicated props, as it's needed for various animations and it's difficult to extract it from style objects. Styles for `TextInput` can be set using `style` prop directly. Released in `0.8.0`.

**Comment by masterpetit** [comment]
Awesome, thanks! @n4kz

**Comment by ilyaivanov** [comment]
Just updated from 0.7 to 0.8.1. Thanks a lot for you efforts in maintaining

**Comment by igor90007** [comment]
"font-family" don't work again.
"version": "0.12.0"

**Comment by eAAwan** [comment]
@igor90007 it works you have pass font family in `style`.
I have just tested with "version": "0.12.0"
