### ISSUE TITLE
Jest fails on 'react-native/package'

### ISSUE THREAD

**Issue by gtRfnkN** [n4kz/react-native-material-textfield#33]
One small thing: when running jest, line 13 of `/src/components/field/index.js` throws the following error: `Cannot find module 'react-native/package' from 'index.js'` [link to file](https://github.com/n4kz/react-native-material-textfield/blob/7ba1c6372e4beb1fec5a32eb5604caf9c6f76432/src/components/field/index.js#L13)

I found that replacing 
`import RN from 'react-native/package';`
with
`import RN from 'react-native/package.json';`
solves that problem.

**Comment by n4kz** [comment]
Sure, released `0.8.1`. Maybe something is wrong with jest setup? Travis and my local installation work with both variants.

**Comment by gtRfnkN** [comment]
I will look into our set-up as well.
But thank you very much for the fast fix 👍
