### ISSUE TITLE
undefined is not an object (evaluating '_reactNative.Animated.Text.propTypes.style') & Animated.Text.propTypes.style problem on react-native-material-textfield

### ISSUE THREAD

**Issue by ghost** [n4kz/react-native-material-textfield#332]
Hi - thank you for this package! Just a quick question: I'm still a little bit new to React Native but I keep encountering an 
"undefined is not an object (evaluating '_reactNative.Animated.Text.propTypes.style and  Animated.Text.propTypes.style' error when I try to use react-native-material-textfield in my project.

The solution provided here: https://stackoverflow.com/questions/61226530/typeerror-undefined-is-not-an-object-evaluating-reactnative-animated-text-pr resolved the error for me but I was wondering if it would be possible to fix this error so we don't have to keep using patch-package to use this package!

Thank you once again 👍

**Comment by gabrieldonadel** [comment]
Hi @calvin-k-ho  unfortunately this is a known bug in `react-native-material-textfield` and this lib appears to be abandoned. 
I suggest you using this fork [rn-material-ui-textfield](https://www.npmjs.com/package/rn-material-ui-textfield) that has fixed this and some other bugs. 

If you want to give it a try just run

```
npm install --save rn-material-ui-textfield

**Comment by ghost** [comment]
@gabrieldonadel Thank you very much - I just switched over to rn-material-ui-textfield, appreciate it. Closing out this ticket 👍
