### ISSUE TITLE
set a touchable besides this component

### ISSUE THREAD

**Issue by thiswhy** [n4kz/react-native-material-textfield#34]
I set A Touchable* besides of this component ,and this component editable={false},when I touch this button,there had no touchable event happend.

**Comment by n4kz** [comment]
Thanks for reporting!

Released fix in `0.8.2`, now pointer events are ignored if field is disabled or not editable, so touchable event should be passed to next responder.

**Comment by thiswhy** [comment]
It's so amazing, my brother! 厉害了我的哥！

**Comment by cinder92** [comment]
@thiswhy this is not working on `    "react-native-material-textfield": "^0.16.1",
`
