### ISSUE TITLE
Different spacing between text and highlight line if multiline={true}

### ISSUE THREAD

**Issue by raynor85** [n4kz/react-native-material-textfield#36]
If your text inside the input doesn't fit in one line, there is a different spacing. When the line increases, the margin is consistent.
Here is the expected correct spacing:
![1 one line](https://user-images.githubusercontent.com/5817333/29224320-b99ee1e2-7ec1-11e7-8584-d91212a00485.png)
If you have more than one line of text, the spacing between the text and the highlight line is too narrow:
![2 two lines](https://user-images.githubusercontent.com/5817333/29224328-be164d78-7ec1-11e7-92c7-0009b5a52c8b.png)

**Comment by n4kz** [comment]
Thanks for reporting! Released fix in `0.8.4`.
