### ISSUE TITLE
Errors Not Being Shown

### ISSUE THREAD

**Issue by mjfox09** [n4kz/react-native-material-textfield#37]
I have been trying to augment the example code to pull it into my application. Currently everything is working with the exception of the error messages not being generated. 

I can pause the debugger before the render method returns and guarantee that my error object has the appropriate error messages contained within it. More than that, if I hard-code an error message onto the Textfield component, it does not render at all.

I can include my code if you would like to take a look at it. I am currently running RN 0.46.1

**Comment by n4kz** [comment]
Thanks for issue! Minimal code sample with described issue will be very useful, as in example project errors are rendered as expected.

**Comment by mjfox09** [comment]
It would probably be best to dump the entirety of the screen that I am trying to implement. I have attached it as a TSX file, a React-Native TypeScript file. This will explain some of the additional code that you had not included in your example, such as the specific mapping of the `errors` object. This was done to alleviate TypeScript errors that were being generated by the linter.

As I believe the code to function, a user should be able to enter an email, a password and then confirm the password. If the password is 6 characters or less, an error will be generated when the CREATE ACCOUNT button is tapped. If the two passwords do not match, an error will be generated for the confirmPassword field. Finally, if any of the fields are blank, an error will be generated. Feel free to ignore the LOGIN WITH FACEBOOK button, as it is not yet implemented.

[AccountCreationScreen.txt](https://github.com/n4kz/react-native-material-textfield/files/1222359/AccountCreationScreen.txt)

**Comment by n4kz** [comment]
Looks like that's a typo in a prop name `<TextField errors={errors.email} />`, should be `error`.

**Comment by mjfox09** [comment]
Ah the difference a single letter makes! Thank you for the assistance.

**Comment by n4kz** [comment]
Glad to help :)
