### ISSUE TITLE
blurOnSubmit should be false if multiline is true

### ISSUE THREAD

**Issue by raynor85** [n4kz/react-native-material-textfield#38]
According to the documentation:
https://facebook.github.io/react-native/docs/textinput.html
blurOnSubmit should be false if multiline is true.
Of course it is possible to pass it explicitly as props, but it would be nice if the default value respects the wrapped native component convention.

**Comment by n4kz** [comment]
Thanks for reporting! Removed default value and released in `0.9.0`.
