### ISSUE TITLE
Make it possible to disable floating labels

### ISSUE THREAD

**Issue by flsilva** [n4kz/react-native-material-textfield#39]
First of all, congrats for the component, it's very nice!

Can you consider making floating labels optional? If we don't provide a `label` param, and provide a `placeholder`, we get the exact visual effect I want. But I get a warning: `Failed prop type: The prop 'label' is marked as required in 'TextField'...`. That's great for places where you want to save some vertical space.

Although MD spec says "Every text field should have a label", I don't think they mean that for its floating state too. If you open Android's built-in contacts and start adding a new one, you'll notice those fields don't have a floating label, just a placeholder.

I could think about two ways to implement that:

A) Just make `label` optional. But if clients don't use placeholder either, we end up with a blank field. If we want to prevent that state we could enforce `label` OR `placeholder` to be present.

B) Add a `floatingLabel={true|false}` extra param (`true` as default to keep consistency).

Let me know what you think.

**Comment by raynor85** [comment]
Just pass an empty string to label. That's what I am doing now, and it works just fine.

**Comment by n4kz** [comment]
Thanks for issue! Agree with @raynor85, empty string seems okay. Label is still rendered and animated, but this should not cause any troubles.
