### ISSUE TITLE
Wrong height resize in multiline

### ISSUE THREAD

**Issue by mxck** [n4kz/react-native-material-textfield#41]
Wrong height if user doesn't use break in input, like this
![simulator screen shot - iphone 6 - 2017-08-22 at 17 26 28](https://user-images.githubusercontent.com/2190443/29561395-7b217c08-875f-11e7-9887-4c4eeee28a3c.png)

**Comment by n4kz** [comment]
Thanks for reporting, this issue affects RN 0.47.0-0.47.1 and was fixed in 0.47.2. I've not found suitable workaround for affected version, so the best solution is to update RN to 0.47.2.
