### ISSUE TITLE
Letter spacing has no effect on value text

### ISSUE THREAD

**Issue by ceyhuno** [n4kz/react-native-material-textfield#42]
`<TextField label={'Hello'} style={{ letterSpacing: 10 }} value={'World'} />`

This should change the letter spacing of the entered text like it does for a normal `TextInput` but it has no effect for `TextField`.

**Comment by n4kz** [comment]
Thanks for reporting. Looks like `letterSpacing` style property works only on `Text` nodes, as I failed to get it working on `TextInput` component using RN 0.47.2. Anyway, `style` property is passed directly to underlying `TextInput` component. If `letterSpacing` starts working at some point on `TextInput`, `TextField` will get it either.
