### ISSUE TITLE
Why characterRestriction limitation doesn't work?

### ISSUE THREAD

**Issue by hosembafer** [n4kz/react-native-material-textfield#43]
I think it will be cool to stop firing onChangeText event when user types new value which length is more than defined characterRestriction.

**Comment by cwalker86** [comment]
@hosembafer since this package is a wrapper around TextInput, you can just set the [maxLength](https://facebook.github.io/react-native/docs/textinput.html#maxlength) prop instead of using characterRestriction.

> maxLength?: number #
>Limits the maximum number of characters that can be entered. Use this instead of implementing the logic in JS to avoid flicker.

**Comment by hosembafer** [comment]
Thanks a lot
