### ISSUE TITLE
TextField underline not showing on Android emulators

### ISSUE THREAD

**Issue by appdevtim** [n4kz/react-native-material-textfield#44]
When testing on both iOS and Android emulators, the iOS shows the underline for the field but the Android emulator does not. Is there a fix for this?

**Comment by appdevtim** [comment]
I solved this issue on my own. Had nothing to do with the component and everything to do with my styling. Had a line height that was causing the issue.

**Comment by abartolo** [comment]
Hi @appdevtim ,

QQ - I am having the same issue but i have not changed any styling to the textfield.

Please see image below. Did you get the same issue?

![image](https://user-images.githubusercontent.com/5394228/30676303-639a93de-9e53-11e7-9c8f-e0fdec094bab.png)

 ```
<View style={CreatePlayerFormStyles.formContainer}>
                <SectionLabel title='Player Details' textStyle={sectionTextStyle} />
                <TextField
                    label='First Name'
                    value={this.state.playerFirstName}
                    error={this.state.errors.playerFirstName}
                    tintColor={Theme.color.scoutlitBlue}
                    onChangeText={(playerFirstName) => this.setState({ playerFirstName })}
                />
                <TextField
                    label='Last Name'
                    value={this.state.playerLastName}
                    error={this.state.errors.playerLastName}
                    tintColor={Theme.color.scoutlitBlue}
                    onChangeText={(playerLastName) => this.setState({ playerLastName })}
                />
                <TextField
                    label='Email'
                    value={this.state.playerEmail}
                    error={this.state.errors.playerEmail}
                    tintColor={Theme.color.scoutlitBlue}
                    onChangeText={(playerEmail) => this.setState({ playerEmail })}
                />
</View>
```

**Comment by LilyMGoh** [comment]
@appdevtim I'm having the same problem as well, but on iOS, and curious on how you solved the problem. I also noticed that when I scroll the lines seem to reappear.

**Comment by abartolo** [comment]
@LilyMGoh I found that if you test on an actual device the lines do appear. For some reason it was only happening in the emulator for me.

**Comment by LilyMGoh** [comment]
Thanks @abartolo! That's good to know.

**Comment by NikhilVashistha** [comment]
@n4kz  I am facing this issue in real devices both Android and iOS. Please let me know if you have any solution for this. 
This issue is coming very frequently.

**Comment by Saumyadip-Pramanik** [comment]
I am also facing this issue in Android real devices.

**Comment by syedamirali14** [comment]
i fixed it with disabledLineWidth={5} or lineWidth={0.5}

**Comment by luizcartolano2** [comment]
@syedamirali14 solution works for me too. Thanks!
