### ISSUE TITLE
blurOnSubmit should be true by default

### ISSUE THREAD

**Issue by loomis17** [n4kz/react-native-material-textfield#45]
Hello! First let me say congrats on an awesome component!

I recently upgraded to v 0.9.0 and now I'm forced to explicitly set blurOnSubmit to true for single-line text inputs. This behavior is opposite to react-native's TextInput:
https://facebook.github.io/react-native/docs/textinput.html#bluronsubmit

I was not experiencing this behavior prior to upgrading.

**Comment by n4kz** [comment]
Thanks for issue. In previous versions `blurOnSubmit` was set to explicitly to `true` in component's `defaultProps`. To fix #38 and to match RN behaviour default value was removed in `0.9.0`. In example `blurOnSubmit` is not set on single line text fields and works as expected with recent RN versions. Please, provide more details or code sample.
