### ISSUE TITLE
add an option to hide line underneath text 

### ISSUE THREAD

**Issue by clickclickonsal** [n4kz/react-native-material-textfield#46]
I want to suggest to either make the dotted line not show when `disabled` is set to `true` or add a property called `showDottedUnderline` which would default to `true` to retain current functionality and thus allow me to hide for my use case.   
I'd like to show something like this.
![image](https://user-images.githubusercontent.com/8260678/30130891-c35b6afa-9318-11e7-8fa7-03768543b382.png)

In my opinion, I think to still have a line underneath text when it is set to `disabled` will give the user the false assumption that the text is still editable. 

I'm happy to submit a PR with this feature request, I would like to know what option I should go with if this makes sense to you as well. 😄

**Comment by n4kz** [comment]
Thanks for issue, hiding underline is now possible since `0.10.0` release. Please take look at new props `disabledLineType` (can be `none`) and `inputContainerStyle`.
