### ISSUE TITLE
KeyboardAvoidingView pushes first field out of the screen

### ISSUE THREAD

**Issue by xvonabur** [n4kz/react-native-material-textfield#48]
I've used the example of this repo. So basically, tap on the first field and you see.

Without **KeyboardAvoidingView**:

<img width="346" alt="screen shot 2017-09-08 at 18 39 46" src="https://user-images.githubusercontent.com/616857/30219575-21088194-94c5-11e7-83a5-2078810e3085.png">

With **KeyboardAvoidingView**:

<img width="343" alt="screen shot 2017-09-08 at 18 39 08" src="https://user-images.githubusercontent.com/616857/30219590-329f2e94-94c5-11e7-9589-32e7858a3273.png">

Here is my changes to the original example: 
https://github.com/xvonabur/react-native-material-textfield/commit/8e8cbdd4f80c6f4a7a010c9cc7318f434917f499

**Comment by xvonabur** [comment]
Hmm, adding `keyboardVerticalOffset={-100}` to `behavior="position"` prop of `KeyboardAvoidingView` works. Also changing `behavior` to another value fixes this bug. So, I think the root of problem was my understaning of `KeyboardAvoidingView` and not your library :)

**Comment by n4kz** [comment]
Thanks for your question, glad to see that everything works as expected :)
