### ISSUE TITLE
Align label and error in center

### ISSUE THREAD

**Issue by ArmandoAssuncao** [n4kz/react-native-material-textfield#50]
Hi,

how i could put label and error in center?

I'm trying this:
```
<TextField
    textAlign="center" // align input text :)
    labelTextStyle={{flex: 1,flexDirection: 'row', flexGrow: 1, textAlign: 'center'}} // not align label :(
    // without prop to error text :(
/>
```

thanks in advance

**Comment by marklcg** [comment]
I ran into the same.  For the label, I was able to do this using inputContainerStyle and alignItems="center", yet to figure out the error text myself.  It seems titleTextStyle should work, but doesn't.

**Comment by n4kz** [comment]
Thanks for question, @marklcg is almost right, just use `textAlign` for `titleTextStyle`.

```javascript
<TextField
  inputContainerStyle={{ alignItems: 'center' }}
  titleTextStyle={{ textAlign: 'center' }}
/>
```

**Comment by ArmandoAssuncao** [comment]
@marklcg @n4kz sorry for delay, btw, your codes worked perfect, thanks :-)

**Comment by UshakovVasilii** [comment]
`titleTextStyle` with `textAlign: 'center'` not work for error without `width: '100%' ` for me.
So `inputContainerStyle={{ alignItems: 'center' }} titleTextStyle={{ textAlign: 'center', width: '100%' }}`
