### ISSUE TITLE
numberOfLines has no effect

### ISSUE THREAD

**Issue by Assem-Hafez** [n4kz/react-native-material-textfield#51]
I'm trying to simulate a `textarea` component using the `TextField`. When i add `numberOfLines` property on the `TextField` no effect takes place.
 ```js
                <TextField
                    label={label}
                    multiline={true}
                    numberOfLines={5} />

```

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. I've tested `numberOfLines` in 0.49.5 and looks like that it works on android only and has very limited use. When line limit is reached you can continue to type, but `TextInput` stops growing. In this component, however, height is manipulated directly and this property takes no effect. I see no easy way of fixing this without support in RN.

**Comment by Assem-Hafez** [comment]
@n4kz Thanks for your great library support
