### ISSUE TITLE
Text Styles not working

### ISSUE THREAD

**Issue by ziyafenn** [n4kz/react-native-material-textfield#52]
Hi there. I've tried to style title and label using the `labelTextStyle` and `titleTextStyle` but nothing happens. Adding i.e. `containerStyle` works fine.

Here is an example of what i'm doing: 

```
inputContainerStyle={styles.inputContainerStyle}
labelTextStyle={styles.label}
titleTextStyle={styles.title}
```
When i enter just `textColor='white'` it works also fine. Thanks!

**Comment by ziyafenn** [comment]
@n4kz any ideas?

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. `*TextStyles` props main purpose lies in text style adjustment, more complex styling is not supported at this moment. I would suggest to make a fork if deep customisation is needed.

**Comment by bertbeck** [comment]
Any progress on this issue? I need to be able to style the label and this seems like a typical need.
