### ISSUE TITLE
Add icon to the left

### ISSUE THREAD

**Issue by odesey** [n4kz/react-native-material-textfield#53]
Is there an easy way to add icon(s) to the left of the input field? Like #28 ?

Thanks for the great work!

**Comment by hosembafer** [comment]
@odesey, you mean like [this](https://user-images.githubusercontent.com/5071289/28661410-93097bb0-72c7-11e7-8e57-e9e81ac10a1c.png)?

**Comment by odesey** [comment]
Yes, just like that.

Thanks.

**Comment by hosembafer** [comment]
Easy way is just create your own component, named for example <Input /> and inside of this write some code like I explain below. Same thing you can do for button component and etc.

```jsx
<View>
    <View>
        <Icon
            name={this.props.iconName}
        />
    </View>
    <View>
        <TextField
            label='TextField'
            value={this.props.value}
        />
    </View>
</View>
```

**Comment by odesey** [comment]
Thanks very much, works great.

Any plans to add this as a feature to the package?

Thanks.

**Comment by hosembafer** [comment]
I don’t think like that. I’m not the maintainer of this repo; to find a more detailed answer for your question you can see the #28 issue’s discussion.

**Comment by hosembafer** [comment]
@odesey, if there are no more questions, can you close issue?

Thanks.

**Comment by numez** [comment]
const IconTextField = (props) => (
      <View>
        <TextField
          {...props}
          labelTextStyle={{ paddingLeft: 32 }}
          inputContainerStyle={{ paddingLeft: 32 }}
        />
        <Icon style={{
          position: 'absolute',
          bottom: 14,
          left: 0,
        }} size={24} name={props.iconName} />
      </View>
    )

**Comment by hamza251** [comment]
Better to use **renderLeftAccessory**
```
<TextField
 {...props}
  renderLeftAccessory={()=>{
    return <Icon 
    size={37} 
    color="#7E7D7D"
    name="user"  />
  }}
/>
```
