### ISSUE TITLE
Focus method doesn't work from refs

### ISSUE THREAD

**Issue by naffiq** [n4kz/react-native-material-textfield#55]
Hi! Thanks for nice component, lots of use!

I've encountered issue when I tried to focus next field with `react-redux` lib.
I saved the function reference to state in `componentDidMount()`:
```js
componentDidMount() {
    this.setState({
      focusPassword: this.refs.passwordField.getRenderedComponent().focus
    });
}
```

And tried to attach it to `onSubmitEditing` prop in `react-redux/Field` component. As a result when I'm trying to press `Next` I get `Cannot read property disabled of undefined` pointing me to this line
[https://github.com/n4kz/react-native-material-textfield/blob/master/src/components/field/index.js#L165](https://github.com/n4kz/react-native-material-textfield/blob/master/src/components/field/index.js#L165)

I noticed that function is not bound (`this.focus = this.focus.bind(this)`) within constructor of component, but instead it has `this.onPress = this.focus.bind(this)`.
After changing my `componentDidMount()` from `focus` to `onPress` everything works as expected.

Documentation on README page seems to refer to `focus` function and `onPress` is not present at all. Looks like either code or docs should be fixed. I suppose it's better to fix code in order to maintain expected behavior after using plain `TextInput` component.

Thanks in advance!

**Comment by n4kz** [comment]
Thanks for question! All methods are not bound to instance, as they should be called directly on component reference, obtained from `ref` callback prop. I have not used redux-forms myself but from your example it's clear that `focus` method passed to `focusPassword` is not bound. It can be fixed like this:

```
componentDidMount() {
    this.setState({
      focusPassword: () => this.refs.passwordField.getRenderedComponent().focus()
    });
}
```

instead of using bound `onPress` callback intended for touch handling purposes.

**Comment by naffiq** [comment]
Thanks for reply!

For example I have this code:

```jsx
    return (
      <View>
        <TextField
          {...inputProps}
          onChangeText={input.onChange}
          onBlur={input.onBlur}
          onFocus={input.onFocus}
          value={input.value}
          ref='textField'
          error={ meta.touched ? meta.error : null }
        />

      </View>
    );
```

And this in my componentDidMount function (as you suggested):
```js
    this.setState({
      focus: this.refs.textField.focus()
    });
```

But when I try to execute this.state.focus function I get:

![](https://api.monosnap.com/rpc/file/download?id=fcnO7i2Fl5bHPvQrvQZtvXonXMzShJ)

I suppose that you added not reference to a function, but the result itself by mistake. So I changed it to:

```js
    this.setState({
      focus: this.refs.textField.focus
    });
```

But now I get this:
![](https://api.monosnap.com/rpc/file/download?id=t86WL9lFUye5XHLuQ0k18JHDM0sjZo)

I know I shouldn't use onPress, at least because it's semantically wrong, but when I change my code to this:

```js
    this.setState({
      focus: this.refs.textField.onPress
    });
```

I get everything just as expected:

![kapture 2017-10-06 at 16 32 09](https://user-images.githubusercontent.com/3990098/31274247-fbcf1d84-aab3-11e7-9661-e5f5394e7738.gif)

I wonder if I don't get something in react lifecycle itself, but it's obvious, that code, that you provided is not working and I hope we can make it so :)

**Comment by evanjmg** [comment]
This is a big issue, might have write my own material input because of this. Basically makes it unusable

**Comment by evanjmg** [comment]
Ah nvm, found the input here: TextField.input  - use this reference. Perhaps put this in the read me to access the ref?

**Comment by naffiq** [comment]
Yeah, that totally needs a PR for Readme

**Comment by velociwabbit** [comment]
I am running into a similar problem that has prevented me from moving to react router 4.0  .  I am removing redux forms but the focus issue is still prevalent.  My question is about how to make the Textfield focus like it did with router 3.0 and redux forms...

It appears that the solution might be related to the TextField.onPress binding or onFocus binding.  

That being said I deliberately use the default options for both which do not link back to redux forms input functions.  And they also do not work to keep focus.

What i want to do is to simply cause the focus to work properly without invoking any of my code to do so.

Is there an option or set of props in TextField that can solve this problem?

**Comment by mquestionable** [comment]
@evanjmg Hey, have you actually succeeded in making input focused? I tried everything and I'm still getting errors when trying to focus input on submitting previous input. Can you share piece of code for this functionality how you made it?

Thanks
