### ISSUE TITLE
Multiline text input style

### ISSUE THREAD

**Issue by adrianicv** [n4kz/react-native-material-textfield#56]
When selecting multiline mode, the line overlaps the input content as you can see in the image below.

![image](https://user-images.githubusercontent.com/7223791/31335792-6b3bc28e-acf4-11e7-8450-6b02e7ab8115.png)

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. Please, provide additional information and sample code if possible. Multiline `TextField` is implemented in [example](https://github.com/n4kz/react-native-material-textfield/tree/master/example) project and has no visual artifacts similar to attached screenshot.

**Comment by tallen11** [comment]
I'm getting the same thing. Text runs outside of the container for some reason. The example it's helpful, it's too simple.

**Comment by jaulz** [comment]
https://github.com/n4kz/react-native-material-textfield/pull/86 will fix this

**Comment by n4kz** [comment]
Merged #86 and released in `0.12.0`. Looks like only rn-web was affected.
