### ISSUE TITLE
Change the bottom light width

### ISSUE THREAD

**Issue by Pensarfeo** [n4kz/react-native-material-textfield#58]
Hi, is there a way to change to width of the bottom line?

Cheers

**Comment by harrisrobin** [comment]
+1

@n4kz perhpas simply allowing us to pass a `lineTextStyle` should do it no?

**Comment by n4kz** [comment]
Thanks for feature request. Added three props `lineWidth` `activeLineWidth` and `disabledLineWidth` and released in `0.11.0`.

**Comment by Pensarfeo** [comment]
Cool, Thanks!
