### ISSUE TITLE
Does it support multiline?

### ISSUE THREAD

**Issue by warka0** [n4kz/react-native-material-textfield#6]
Hi,

I guess i do it wrong... So i'm just asking for help or informations.
When i set multiline={true} and try to press return, the text input doesn't grow in height and it unfocus. 

Is it normal? Or there is another way?

Thx !

**Comment by warka0** [comment]
Nevermind, by commenting this line, the text input grow... 
I guess there is a conflict with props.
`// {...props}`

**Comment by warka0** [comment]
<TextInput
	            style={[ styles.input, inputStyle, style, { flex:1} ]}
	            selectionColor={tintColor}

	            // editable = {true}
	            multiline={this.props.multiline}

	            // {...props}

	            editable={!disabled && editable}

	            onChangeText={this.onChangeText}
	            onContentSizeChange={this.onContentSizeChange}
	            onFocus={this.onFocus}
	            onBlur={this.onBlur}
	            value={text}
	            ref='input'
	          />

**Comment by warka0** [comment]
Ok,

I've found a fix!
There is a problem with onSubmitEditing and multiline.
Instead of pushing ...props, i've fixed it by making this : 

let options = {
	onSubmitEditing: this.props.onSubmitEditing
}
if (!this.props.onSubmitEditing) {
	options = {}
}

and do {...options}

If someone else has the same problem...

**Comment by n4kz** [comment]
Thanks for reporting, this behaviour is described in [docs](https://facebook.github.io/react-native/docs/textinput.html#bluronsubmit). Probably I should not set `blurOnSubmit` prop to `true` by default for all field types. Please, let me know if setting it to `false` explicitly solves this issue.

**Comment by warka0** [comment]
Ok thx!
