### ISSUE TITLE
Predefined validations

### ISSUE THREAD

**Issue by adrianicv** [n4kz/react-native-material-textfield#61]
Are there any plans to include predefined validations such as required field validation, email validation, phone validation. I think it would improve the textfield functionality.

As an example I think that the user should be able to indicate through a `required` prop if the field is required and other prop to tell the component when a submit action is fired.

```
<TextField label="Required example" 
          required 
          submitted={submitted}
          onChangeText={(value) => {this.setState({value})}
          value={value}/>
```

**Comment by evertoncastro** [comment]
I agree with @adrianicv. The validations would be a great feature for this library. Could you suggest some way to use validation at this moment? The only way I could figure it out was creating my own function validations and bind it on the field component. I think the same for masks. thanks!

**Comment by adrianicv** [comment]
For now, I've created a wrapper that handles several validations such as require field, email validation, ...

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. I'm completely sure that validations would be a great addition but are out of scope for this component as validation requirements differ from app to app. Will be happy to participate in integration with any existing form library. I'm using some homemade wrappers myself, so actually can not recommend anything right now.
