### ISSUE TITLE
How to show error message

### ISSUE THREAD

**Issue by AndreBastos23** [n4kz/react-native-material-textfield#65]
Hello,

could you do a simple example on how to append an error message depending on the value of the field?

**Comment by naffiq** [comment]
@AndreBastos23 

I believe it's just an `error: string` prop.

**Comment by AndreBastos23** [comment]
Thank you, you are right. What is the best way to validate a field after the user writes on it?

**Comment by naffiq** [comment]
@AndreBastos23 

I'm using `redux-form`, which has validator support, that works with this component just great.
If you are not using redux, then you can try this one https://github.com/gcanti/tcomb-form-native

**Comment by n4kz** [comment]
Thanks for question. @naffiq thanks for detailed explanation.
Looks like this can be closed.
