### ISSUE TITLE
disabledLineType not working because of a RN issue

### ISSUE THREAD

**Issue by ricbermo** [n4kz/react-native-material-textfield#67]
Hello,

Right now there's an issue with RN, the `borderStyle` is always printed like `solid` no matter witch value you set. The workaround for that issue is to set `borderRadius` > 0. The `Line` component, which handles that, doesn't receive any prop that could help us fix the issue. The way to go is to modify ourselves the Line component styles and to use a tool called `patch-package`.

**Comment by n4kz** [comment]
Thanks for reporting! Fixed and released in `0.10.2`.

Issue was solved in RN few releases ago but broken again afterwards.
