### ISSUE TITLE
How to vertical center and horizontal center

### ISSUE THREAD

**Issue by maac4422** [n4kz/react-native-material-textfield#68]
How I can center vertical and horizontal the <TextField/> inside the screen.

I try this.

![captura de pantalla 2017-10-29 a la s 2 51 08 p m](https://user-images.githubusercontent.com/15006454/32147677-1cbb6176-bcb9-11e7-98ed-2126a61b5eb8.png)

This it's result

![captura de pantalla 2017-10-29 a la s 2 50 28 p m](https://user-images.githubusercontent.com/15006454/32147682-2a9de0b6-bcb9-11e7-843c-685bc2c93978.png)

I can't see what I write

**Comment by n4kz** [comment]
Thanks for question, please try the following:

```javascript
<View style={{ alignItems: 'center', justifyContent: 'center', flex: 1 }}>
  <TextField containerStyle={{ width: 240 }} />
<View>
```

As an alternative `flexDirection: 'row'` can be used for container view with `flex: 1` set on `TextField`. Minimal width is not set on `TextField`, so you have to set it explicitly or have horizontal flex or pin sides with absolute positioning.

**Comment by maac4422** [comment]
Thanks @n4kz  .I fixed it using this style ` formSyle: {
        flex: 1,
        alignSelf: 'center',
        justifyContent: 'center'
    },`  and set it at the View tag
