### ISSUE TITLE
Possibility to show affix text at the end of current cursor position

### ISSUE THREAD

**Issue by jhalborg** [n4kz/react-native-material-textfield#71]
Hello, 

First of all, thank you for a great library!

Question/feature request: Would it be possible for the affix text to stay after the input text, and move with it? The use case is for the user to input a caption or an instagram post, and for one or more hashtags to be obligatory for the caption. I.e.

```The input here followed by #sometag #andsomeothertag ```

I hope it makes sense. Maybe it's already possible and I missed it. I see there's an option for styling it, and if I could make the affix text show at the bottom of the textinput (multiline) and always be one line below the cursor, it would work, too, but I can't figure out how to do it. 

Thanks again!

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. This is a challenging task. I would suggest using [`onContentSizeChange`](https://github.com/n4kz/react-native-material-textfield/blob/70b8f132913f1feba11dfd9f3628e892a971500a/src/components/field/index.js#L252) prop to get text dimensions and container with absolute position attached to same parent as `TextField` itself.

```javascript
<View>
  <TextField onContentSizeChange={...} />
  <View style={{ position: 'absolute', top: 32 /* depends on label height */, left: 0 }}>
    <View style={/* dynamic padding */} />
    <Text>#hashtag</Text>
</View>
```
