### ISSUE TITLE
prop type `style` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`

### ISSUE THREAD

**Issue by piranna** [n4kz/react-native-material-textfield#75]
With latest ReactNative 0.50 I'm getting that warning message both for `Label` and `Helper` component. Seems the definition of `Animated.Text.propTypes.style` used at https://github.com/n4kz/react-native-material-textfield/blob/e04ffdc882b391fc145b3fc2421ef6c5dd7bc66d/src/components/label/index.js#L32 and https://github.com/n4kz/react-native-material-textfield/blob/e04ffdc882b391fc145b3fc2421ef6c5dd7bc66d/src/components/helper/index.js#L13 from ReactNative have changed, although I can't be able to find what's the current new one (maybe is it https://github.com/facebook/react-native/blob/d5b59517c274874d7ce21e5c26d28b42ae389723/Libraries/Text/Text.js#L367 / [stylePropType](https://github.com/facebook/react-native/blob/d5b59517c274874d7ce21e5c26d28b42ae389723/Libraries/Text/Text.js#L30)?).

**Comment by n4kz** [comment]
Thanks for reporting, I've checked RN 0.50.3 and have not received described warning. Please, provide more info or sample code.

**Comment by mayurbaldha** [comment]
@n4kz   problem persists with "react-native": "0.62.2",

**Comment by DnEgorWeb** [comment]
Same here, shows the warning with `0.62`

**Comment by GrinchakAndrew** [comment]
Why is this closed?

**Comment by raldred** [comment]
Still present in 0.63.3

![image](https://user-images.githubusercontent.com/37096/99827003-ff90f480-2b50-11eb-9494-381f3a662e77.png)

**Comment by d-es-ign** [comment]
Any update on this issue?

**Comment by gabrieldonadel** [comment]
Hi @d-es-ign, unfortunately this is a known bug in `react-native-material-textfield` and this lib appears to be abandoned. 
I suggest you using this fork [rn-material-ui-textfield](https://www.npmjs.com/package/rn-material-ui-textfield) that has fixed this and some other bugs. 

If you want to give it a try just run

```
npm install --save rn-material-ui-textfield
