### ISSUE TITLE
ScrollView not scrolling to a field

### ISSUE THREAD

**Issue by slawek-mazur** [n4kz/react-native-material-textfield#76]
Is there any way to deal with large forms with many fields which get covered by keyboard? I tired `react-native-material-textfield` with https://github.com/APSL/react-native-keyboard-aware-scroll-view but with no luck.

**Comment by kadoshms** [comment]
What about the RN out of the box `KeyboardAvoidingView`?

**Comment by n4kz** [comment]
Thanks for question. For this moment I'm not using anything special for large forms except `android:windowSoftInputMode="adjustResize"` on Android. I also had used `Keyboard` from RN to determine keyboard frame size.
