### ISSUE TITLE
please add rtl prop

### ISSUE THREAD

**Issue by uxitten** [n4kz/react-native-material-textfield#78]
for arabic and farsi
ex:
```
<TextField
                        textColor={configs.colors.white}
                        fontSize={14}
                        label='عنوان هدف'
                        rtl={true}
                    />
```

**Comment by uxitten** [comment]
with change this code:

let inputContainerProps = {
      style: [
        styles.inputContainer,
        inputContainerStyle,
        inputContainerStyleOverrides,
        {
          alignItems: rtl ? 'flex-end' : 'flex-start'
        }
      ],
    };

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. I've added basic RTL detection using `I18nManager` module from RN. Should work without any additional props on RTL locales or with `I18nManager.forceRTL(true)`. Released in `0.12.0`.

**Comment by gabrielmoncea** [comment]
@n4kz what about label and error message?

**Comment by mrxrinc** [comment]
@n4kz Please please merge @uxitten 's code to the master, it works perfectly with label.

**Comment by pedrobernardina** [comment]
It would be good to have this as prop as well. Monetary input is usually read from right to left, and I wouldn't like to use i18n manager to support rtl for just a couple of inputs.
