### ISSUE TITLE
Bottom Line Color when filled.

### ISSUE THREAD

**Issue by newfylox** [n4kz/react-native-material-textfield#79]
Hi, I was wondering if there's a way to set the bottom line color when textfield is filled, or at least has some characters in it?

I'm talking when the focus is out. So instead of a gray line, it could be a black line because there are characters in it.

Thanks

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. There is no easy way of doing this right out of the box, but I can suggest to update `baseColor` prop value in `onChangeText` callback.
