### ISSUE TITLE
Extra space on top

### ISSUE THREAD

**Issue by hassanrazakhalid** [n4kz/react-native-material-textfield#81]
Hello please help me out why textField has extra height on top. I have 2 textFields but they have extra top margin EY2010102 and enter regMobileNo
![simulator screen shot - iphone 7 - 2017-12-23 at 14 18 36](https://user-images.githubusercontent.com/15266641/34318904-41891eea-e7ec-11e7-990c-a8f390b1909e.png). 
i m using following code

```
 {FormComponents.getTextField('EY2010102', (text => this.setState({ idValue: text })))}
{FormComponents.getTextField('Enter Registered mobile no', (text => this.setState({ registeredMobileNo: text })))}
```
 And in form component class
```
static getTextField = (placeHolder, onChangeText, errorText = '' ) => {
       return (
        <TextField
              style={[
                { color: BasicStyle.TextGrayColor, height: GlobalConstants.textFieldHeight },
                Font.getFont(Font.Lato, Weight.Medium)
              ]}
              
              label={placeHolder}
              underlineColorAndroid="transparent"
              onChangeText={onChangeText}
              error={errorText}
              tintColor={BasicStyle.PrimaryGreen}
              baseColor={BasicStyle.Gray}
            />
       )
   }
```
Even after selecting value i still find extraTop margin.

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. Top padding can be adjusted using `labelHeight` prop. Please, take look at n4kz/react-native-material-textfield#30 for details.
