### ISSUE TITLE
Is there a way to always have the suffix shown?

### ISSUE THREAD

**Issue by VicFrolov** [n4kz/react-native-material-textfield#82]
Would be nice to have an icon in the far right always being displayed like so:

<img width="265" alt="screen shot 2017-12-25 at 3 00 10 pm" src="https://user-images.githubusercontent.com/8305711/34343465-59b99f14-e984-11e7-907e-75bb5d0dcbd6.png">

Unsure how to do this with react-native-material-textfield though. I tried adding an icon to the right or left using views and flex, but the problem is the underline of the textfield then doesn't go under it so it deosn't look as clean.

**Comment by AunMSheikh** [comment]
I have used the View with Textfield followed by an image and it works like a charm. You need to give your image a position of absolute. My stylings for the image are: 
`   height: 14, 
    width: 14, 
    position: 'absolute', 
    right: 2, 
    bottom: 18,
    zIndex: 12`

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. Icon can be added to `TextField` via `renderAccessory` prop. For implementation details please take look at [example project](https://github.com/n4kz/react-native-material-textfield/blob/master/example/app.js#L124).
