### ISSUE TITLE
Clicking outside the Textfield doesn't works

### ISSUE THREAD

**Issue by Abydars** [n4kz/react-native-material-textfield#84]
While the Textfield is in focus, and if I try to click any button or try to change focus, I have to click twice on that. Please help, how can I get rid of this issue?

`<TextField
                            label='Pickup Address'
                            tintColor={Colors.orange}
                            textColor={Colors.orange}
                            value={this.state.pickup}
                            ref={(input) => this.pickup = input}
                            onFocus={() => this.pickup.focus()}
                            onSubmitEditing={() => this.drop.focus()}
                            onChangeText={(pickup) => this.updateState({ pickup })}
                            autoCapitalize="words"
                            dataDetectorTypes="address"
                            returnKeyType='next'
                        />`

**Comment by RobertSheaO** [comment]
@Abydars This is common issue when putting a TextField inside a `ScrollView`, `ListView`, or `FlatList`. It's because the first click (by default) is to dismiss the keyboard. Sounds like you might need to use the `always` or `handled` option. Take a look at the documentation link below!

https://facebook.github.io/react-native/docs/scrollview.html#keyboardshouldpersisttaps

**Comment by n4kz** [comment]
Thanks for question!

@RobertSheaO thanks for great answer, I'll add this prop to example project.

**Comment by PesciSports** [comment]
@RobertSheaO Actually, the keyboard gets dismissed, but it is not focusing the current tap element.
example,
tap on Username field, entered Username...
now tap on Password, should dismiss the keyboard and focus on Password field but it is only dismissing the keyboard not focusing the next field.
The Go button on the keyboard, works good, but direct tapping doesn't works.

**Comment by Abydars** [comment]
@RobertSheaO Actually, the keyboard gets dismissed, but it is not focusing the current tap element.
example,
tap on Username field, entered Username...
now tap on Password, should dismiss the keyboard and focus on Password field but it is only dismissing the keyboard not focusing the next field.
The Go button on the keyboard, works good, but direct tapping doesn't works.
