### ISSUE TITLE
No decimals on numeric keyboard on android api 25

### ISSUE THREAD

**Issue by gabsima-nexapp** [n4kz/react-native-material-textfield#87]
Numeric keyboard of a TextInput :
![screenshot_20180118-112623 2](https://user-images.githubusercontent.com/32681197/35109109-6a2bd520-fc43-11e7-80ab-10c8c42bc846.jpg)

Numeric keyboard of a TextField : 
![screenshot_20180118-112634 2](https://user-images.githubusercontent.com/32681197/35109130-7691e796-fc43-11e7-99df-3b5e82b2a839.jpg)

**Comment by gabsima-nexapp** [comment]
Looks like it is a Samsung issue.

**Comment by elly0t** [comment]
I'm encountering this issue on Samsung devices as well. Have you found a solution? Thanks in advance.

**Comment by gabsima** [comment]
I'm afraid not, i ended up writing my own component using a TextInput. I did not put the effort to add the label animation, but it changes color when focusing on it. I could send it to you if you want?

**Comment by elly0t** [comment]
I ended up writing a built-in num pad (literally a view wrapping num pad grids) to solve this. Would still like to have a look at your code tho, thanks ;)
