### ISSUE TITLE
secureTextEntry not working on Android

### ISSUE THREAD

**Issue by hugomosh** [n4kz/react-native-material-textfield#92]
The ** secureTextEntry** prop works on iOS but not for android.

react-native-cli: 2.0.1
react-native: 0.52.0
react-native-material-textfield@^0.12.0

**Comment by BrandonWilliamsCS** [comment]
Is this possibly the issue you're seeing?
https://github.com/facebook/react-native/issues/17248
A fix for that issue has been merged into react-native and (if all goes well) is probably going to arrive in the version after 0.53.0. A workaround is to *not* use `keyboardType` of `"visible-password"` alongside `secureTextEntry`.

Another possible issue is that RN doesn't may not properly support `secureTextEntry` with certain keyboard types like `"email-address"`.
https://github.com/facebook/react-native/issues/15319

Personally, I'm not noticing any other `secureTextEntry` issues on Android for version 0.12.0. If neither case applies to you, consider adding more detail so the library's author can better diagnose the problem.

**Comment by n4kz** [comment]
Thanks for issue! I've tested example project with RN `0.51.0` and can say that `secureTextEntry` works as expected on Android. Probably the best option for now is to use older RN versions and wait for next major RN release.

@BrandonWilliamsCS thanks for research and great explanation!

**Comment by ramonprata** [comment]
for anyone who has still getting problem, a simple workaround
