### ISSUE TITLE
First 4-5 characters are hiding

### ISSUE THREAD

**Issue by vkmulloly** [n4kz/react-native-material-textfield#95]
I am using react-native-material-textfield for my project if the string is more than 30 character  then first 4-5 character is hiding at the beginning  , how to show the string from the beginning ,i dont want to make text field as multi line

**Comment by esutton** [comment]
+1 

On Android, the last part of a long string is displayed and first part is hidden.

Is this a Google Material Design guideline?

### What I Expected:

String is displayed from the beginning and last part of a long string will be hidden.

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. This is expected behavior for both platforms.

**Comment by ff-joaquin-rojas** [comment]
+1 
It is having different behaviour on iOS and Android.
On iOS it is working as expected, setting the cursor to the start of the string. 
For Android, it is not setting the curso the the start of the string, but at the end.
Checking the Google Material Design guideline, I can confirm this is not working as expected for Android.

A workaround I did to have the desired behaviour was  getting the ref of the component and then:
```
ref={(ref) => {
                ref.focus()
                ref.blur()
              }
    }
```

Hope it helps in the meantime.

**Comment by esutton** [comment]
@ff-joaquin-rojas What version were you seeing the Android problem?

**Comment by ff-joaquin-rojas** [comment]
@esutton I'm using 0.12.0.  I just noticed that it is not the latest one. (Not really sure if the problem is fixed on the latest version)
