### ISSUE TITLE
[BUG] wrong position

### ISSUE THREAD

**Issue by tvhieuit** [n4kz/react-native-material-textfield#96]
I clicked Email field but position wrong same as image 

```
<TextField
          multiline={false}
          label='EMAIL'/>
<TextField
          multiline={false}
          label='PASSWORD'/>
```

![simulator screen shot - iphone 6 - 2018-02-09 at 09 46 35](https://user-images.githubusercontent.com/12293328/36009285-2246f310-0d7e-11e8-8261-c0d0b3d4f400.png)

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. Please, take a look at recent release `0.13.0`. If problem still exists please let me know by updating this issue or creating a new one.
