### ISSUE TITLE
Empty space when no label

### ISSUE THREAD

**Issue by piranna** [n4kz/react-native-material-textfield#97]
When `label` is not set, it left an empty space over the textfield. I have found a hack by setting `labelHeight=0`, but probably this would be done automatically by textfield and maybe also in this case do some side optimizations like dissabling label animations and similar ones.

**Comment by piranna** [comment]
Ok, I've just seen in the console the error 'Warning: Failed prop type: The prop `label` is marked as required in `TextField`, but its value is `undefined`.' For my case I don't want a label because I'm composing a new component and the label will be in a button right to the textfield (the textfield is readonly and works mostly as a contextual label for the button, but I want it to have the same aesthetics of the other textfields), so is there any other correct way to do it?

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. For now there is no right way to do it. I'm planning to fix this at some point in near future along with outline mode support.
