### ISSUE TITLE
Not playing nicely as a controlled component

### ISSUE THREAD

**Issue by Noitidart** [n4kz/react-native-material-textfield#98]
I am making my field a controlled component by controling the value property. Like this:

```
render() {
<TextField value={value} />
}
```

This `value` is kept in my redux store.

In my `onChangeText` I dispatch an update to the value in my redux store, only if the user entered a good value. If they entered a bad value I dont update my store. However react-native-material-textfield seems to maintain its own `state` with the `this.state.text`.

Is there any advice on how to tell it to not use `this.state.text` but instead rely on changes to `this.props.value`?

**Comment by Noitidart** [comment]
I acheived full control by changing here:

https://github.com/n4kz/react-native-material-textfield/blob/master/src/components/field/index.js#L367

I changed this:

```
    value = defaultVisible?
      defaultValue:
      text;
```

to this:

```
    value = defaultVisible?
      defaultValue:
      value; ///// this was changed from text to value
```

Will this break anything? Should I make a PR to change this to "if we have `value` in props, then it should use value here, else use text"? So like:


```
    value = defaultVisible?
      defaultValue:
      ('value' in props ? value : text); ///// should we make this change?
```

**Comment by petrogad** [comment]
Would love to see a PR against this too.  Thanks for identifying @Noitidart

**Comment by Noitidart** [comment]
Thanks @petrogad!

**Comment by Noitidart** [comment]
@petrogad i made PR for this just now - https://github.com/younited/trustedplatform_android/commit/71d2f81ff368d01ff7e6894148c173a28b9d4b1d - these changes make it work, but i dont know if its right

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. I've made this component fully uncontrolled in 99d1178 with an option to update value via `setValue` method.
